/*
*  This unpublished work, first created in 2017 and updated thereafter,
*  is protected under the copyright laws of the United States and of
*  other countries throughout the world.  Use, disassembly, reproduction,
*  distribution, etc. without the express written consent of United
*  Technologies Corporation is prohibited.  Copyright United Technologies
*  Corporation 2017.  All rights reserved.  Information contained herein
*  is proprietary and confidential and improper use or disclosure may
*  result in civil and penal sanctions.
*
*  File:    CompareToolDaoPW.java
*  
*  PW_SMRO_eWORK_202-Order-Creation
* 
*  Created: 2018.08.07
* 
*  Author:  Thien-Long Phan
* 
*  Revision History
* 
*  Date             Who            Description
*  -----------    ------------     ---------------------------------------------------
*  2018-07-08     Thien-Long Phan  Defect 880. Order Compare displays PW_ORDER_NO
*/
package com.pw.solumina.sfpl.dao;

import java.util.Map;

import com.ibaset.common.Reference;
import com.ibaset.common.dao.JdbcDaoSupport;
import com.ibaset.common.sql.ParameterHolder;

public class CompareToolDaoPW
{
	@Reference private JdbcDaoSupport eds;
	
	public Map selectOrderInformation(String orderId)
    {
        StringBuffer selectSql = new StringBuffer().append("SELECT ")
                                                   .append("    B.PW_ORDER_NO, ") //Changed to PW_ORDER_NO instead of ORDER_NO. Defect 880
                                                   .append("    A.ORDER_TYPE, ")
                                                   .append("    A.NEEDS_REVIEW_FLAG, ")
                                                   .append("    A.ORDER_CUST_ID, ")
                                                   .append("    A.PLAN_ID, ")
                                                   .append("    A.PLAN_VERSION, ")
                                                   .append("    A.PLAN_REVISION, ")
                                                   .append("    A.PLAN_ALTERATIONS, ")
                                                   .append("    A.PLAN_UPDT_NO, ")
                                                   .append("    A.ORDER_STATUS, ")
                                                   .append("    A.ORDER_HOLD_STATUS, ")
                                                   .append("    CASE WHEN A.ASGND_LOCATION_ID IS NULL THEN NULL ")
                                                   .append(" 	ELSE ( SELECT WORK_LOC FROM SFFND_WORK_LOC_DEF S WHERE S.LOCATION_ID = ASGND_LOCATION_ID ) END AS ASGND_WORK_LOC, ") // FND-22681
                                                   .append("    A.ORDER_QTY, ")
                                                   .append("    A.SCHED_PRIORITY, ")
                                                   .append("    A.INITIAL_STORES, ")
                                                   .append("    A.FINAL_STORES, ")
                                                   .append("    A.CONTRACT_NO, ")
                                                   .append("    A.PARENT_ORDER_ID, ")
                                                   .append("    A.ORIG_ORDER_ID, ")
                                                   .append("    A.SUPERCEDED_ORDER_ID, ")
                                                   .append("    A.SUPERCEDES_ORDER, ")
                                                   .append("    A.SPLIT_FLAG, ")
                                                   .append("    A.SCHED_START_DATE, ")
                                                   .append("    A.SCHED_END_DATE, ")
                                                   .append("    A.REVISED_START_DATE, ")
                                                   .append("    A.REVISED_END_DATE, ")
                                                   .append("    A.ACTUAL_START_DATE, ")
                                                   .append("    A.ACTUAL_END_DATE, ")
                                                   .append("    A.UNIT_NO, ")
                                                   .append("    A.CUSTOMER_ORDER_NO, ")
                                                   .append("    A.SERIAL_FLAG, ")
                                                   .append("    A.LOT_FLAG, ")
                                                   .append("    A.PLAN_TYPE, ")
                                                   .append("    A.ORDER_TYPE, ")
                                                   .append("    A.ITEM_ID, ")
                                                   .append("    A.PART_NO, ")
                                                   .append("    A.PART_CHG, ")
                                                   .append("    A.ITEM_TYPE, ")
                                                   .append("    A.ITEM_SUBTYPE, ")
                                                   .append("    A.PROGRAM, ")
                                                   .append("    A.MFG_BOM_CHG, ")
                                                   .append("    A.MODEL, ")
                                                   .append("    A.PLAN_TITLE, ")
                                                   .append("    A.ORDER_UOM, ")
                                                   .append("    A.UNIT_TYPE, ")
                                                   .append("    A.PROJECT, ")
                                                   .append("    A.ALT_ID, ")
                                                   .append("    A.ALT_COUNT, ")
                                                   .append("    A.ALT_STATUS, ")
                                                   .append("    A.ALTER_TYPE, ")
                                                   .append("    A.ENG_PART_NO, ")
                                                   .append("    A.ENG_PART_CHG, ")
                                                   .append("    A.ENG_GROUP, ")
                                                   .append("    A.MFG_INDEX_NO, ")
                                                   .append("    A.PLG_GROUP, ")
                                                   .append("    A.LTA_SEND_FLAG, ")
                                                   .append("    A.OPER_SEQ_FLAG, ")
                                                   .append("    A.UNSCRAP_FLAG, ")
                                                   .append("    A.STATUS_CHG_REASON, ")
                                                   .append("    A.STATUS_CHG_NOTES, ")
                                                   .append("    A.EXTERNAL_PLM_NO, ")
                                                   .append("    A.EXTERNAL_ERP_NO, ")
                                                   .append("    A.CONDITION, ")
                                                   .append("    A.BOM_NO, ")
                                                   .append("    A.UCF_PLAN_VCH1, ")
                                                   .append("    A.UCF_PLAN_VCH2, ")
                                                   .append("    A.UCF_PLAN_VCH3, ")
                                                   .append("    A.UCF_PLAN_VCH4, ")
                                                   .append("    A.UCF_PLAN_VCH5, ")
                                                   .append("    A.UCF_PLAN_VCH6, ")
                                                   .append("    A.UCF_PLAN_VCH7, ")
                                                   .append("    A.UCF_PLAN_VCH8, ")
                                                   .append("    A.UCF_PLAN_VCH9, ")
                                                   .append("    A.UCF_PLAN_VCH10, ")
                                                   .append("    A.UCF_PLAN_VCH11, ")
                                                   .append("    A.UCF_PLAN_VCH12, ")
                                                   .append("    A.UCF_PLAN_VCH13, ")
                                                   .append("    A.UCF_PLAN_VCH14, ")
                                                   .append("    A.UCF_PLAN_VCH15, ")
                                                   .append("    A.UCF_PLAN_VCH255_1, ")
                                                   .append("    A.UCF_PLAN_VCH255_2, ")
                                                   .append("    A.UCF_PLAN_VCH255_3, ")
                                                   .append("    A.UCF_PLAN_VCH4000_1, ")
                                                   .append("    A.UCF_PLAN_VCH4000_2, ")
                                                   .append("    A.UCF_PLAN_FLAG1, ")
                                                   .append("    A.UCF_PLAN_FLAG2, ")
                                                   .append("    A.UCF_PLAN_FLAG3, ")
                                                   .append("    A.UCF_PLAN_FLAG4, ")
                                                   .append("    A.UCF_PLAN_FLAG5, ")
                                                   .append("    A.UCF_PLAN_NUM1, ")
                                                   .append("    A.UCF_PLAN_NUM2, ")
                                                   .append("    A.UCF_PLAN_NUM3, ")
                                                   .append("    A.UCF_PLAN_NUM4, ")
                                                   .append("    A.UCF_PLAN_NUM5, ")
                                                   .append("    A.UCF_PLAN_DATE1, ")
                                                   .append("    A.UCF_PLAN_DATE2, ")
                                                   .append("    A.UCF_PLAN_DATE3, ")
                                                   .append("    A.UCF_PLAN_DATE4, ")
                                                   .append("    A.UCF_PLAN_DATE5, ")
                                                   .append("    A.UCF_ORDER_VCH1, ")
                                                   .append("    A.UCF_ORDER_VCH2, ")
                                                   .append("    A.UCF_ORDER_VCH3, ")
                                                   .append("    A.UCF_ORDER_VCH4, ")
                                                   .append("    A.UCF_ORDER_VCH5, ")
                                                   .append("    A.UCF_ORDER_VCH6, ")
                                                   .append("    A.UCF_ORDER_VCH7, ")
                                                   .append("    A.UCF_ORDER_VCH8, ")
                                                   .append("    A.UCF_ORDER_VCH9, ")
                                                   .append("    A.UCF_ORDER_VCH10, ")
                                                   .append("    A.UCF_ORDER_VCH11, ")
                                                   .append("    A.UCF_ORDER_VCH12, ")
                                                   .append("    A.UCF_ORDER_VCH13, ")
                                                   .append("    A.UCF_ORDER_VCH14, ")
                                                   .append("    A.UCF_ORDER_VCH15, ")
                                                   .append("    A.UCF_ORDER_VCH255_1, ")
                                                   .append("    A.UCF_ORDER_VCH255_2, ")
                                                   .append("    A.UCF_ORDER_VCH255_3, ")
                                                   .append("    A.UCF_ORDER_VCH4000_1, ")
                                                   .append("    A.UCF_ORDER_VCH4000_2, ")
                                                   .append("    A.UCF_ORDER_FLAG1, ")
                                                   .append("    A.UCF_ORDER_FLAG2, ")
                                                   .append("    A.UCF_ORDER_FLAG3, ")
                                                   .append("    A.UCF_ORDER_FLAG4, ")
                                                   .append("    A.UCF_ORDER_FLAG5, ")
                                                   .append("    A.UCF_ORDER_NUM1, ")
                                                   .append("    A.UCF_ORDER_NUM2, ")
                                                   .append("    A.UCF_ORDER_NUM3, ")
                                                   .append("    A.UCF_ORDER_NUM4, ")
                                                   .append("    A.UCF_ORDER_NUM5, ")
                                                   .append("    A.UCF_ORDER_DATE1, ")
                                                   .append("    A.UCF_ORDER_DATE2, ")
                                                   .append("    A.UCF_ORDER_DATE3, ")
                                                   .append("    A.UCF_ORDER_DATE4, ")
                                                   .append("    A.UCF_ORDER_DATE5, ")
                                                   .append("    A.DISPLAY_SEQUENCE, ")
                                                   .append("    A.SECURITY_GROUP ")
                                                   .append("    ,A.OPERATION_OVERLAP_FLAG ") // FND-22135
                                                   .append(" FROM ")
                                                   .append("    SFWID_ORDER_DESC A, PWUST_SFWID_ORDER_DESC B ")  //B is where PW_ORDER_NO is. Defect 880
                                                   .append(" WHERE ")
                                                   .append("    A.ORDER_ID = ? AND ")
                                                   .append("    A.ORDER_ID = B.ORDER_ID ");

        ParameterHolder params = new ParameterHolder();
        params.addParameter(orderId);

        return eds.queryForMap(selectSql.toString(), params);
    }
	public Map selectOrderInformationAltLog ( String orderId,
            String altId )
	{
    		StringBuffer selectSql = new StringBuffer().append("SELECT ")
                 .append("    B.PW_ORDER_NO, ") //Changed to PW_ORDER_NO instead of ORDER_NO. Defect 880
                 .append("    A.ORDER_TYPE, ")
                 .append("    A.NEEDS_REVIEW_FLAG, ")
                 .append("    A.ORDER_CUST_ID, ")
                 .append("    A.PLAN_ID, ")
                 .append("    A.PLAN_VERSION, ")
                 .append("    A.PLAN_REVISION, ")
                 .append("    A.PLAN_ALTERATIONS, ")
                 .append("    A.PLAN_UPDT_NO, ")
                 //.append("    ORDER_STATUS, ")
                 //.append("    ORDER_HOLD_STATUS, ")
                 .append("    CASE WHEN A.ASGND_LOCATION_ID IS NULL THEN NULL ")
                 .append("    ELSE ( SELECT WORK_LOC FROM SFFND_WORK_LOC_DEF S WHERE S.LOCATION_ID = ASGND_LOCATION_ID ) END AS ASGND_WORK_LOC, ")
                 .append("    A.ORDER_QTY, ")
                 .append("    A.SCHED_PRIORITY, ")
                 .append("    A.INITIAL_STORES, ")
                 .append("    A.FINAL_STORES, ")
                 .append("    A.CONTRACT_NO, ")
                 //.append("    PARENT_ORDER_ID, ")
                 //.append("    ORIG_ORDER_ID, ")
                 //.append("    SUPERCEDED_ORDER_ID, ")
                 //.append("    SUPERCEDES_ORDER, ")
                 .append("    A.SPLIT_FLAG, ")
                 //.append("    SCHED_START_DATE, ")
                 //.append("    SCHED_END_DATE, ")
                 //.append("    REVISED_START_DATE, ")
                 //.append("    REVISED_END_DATE, ")
                 //.append("    ACTUAL_START_DATE, ")
                 //.append("    ACTUAL_END_DATE, ")
                 .append("    A.UNIT_NO, ")
                 .append("    A.CUSTOMER_ORDER_NO, ")
                 .append("    A.SERIAL_FLAG, ")
                 .append("    A.LOT_FLAG, ")
                 .append("    A.PLAN_TYPE, ")
                 .append("    A.ORDER_TYPE, ")
                 .append("    A.ITEM_ID, ")
                 .append("    A.PART_NO, ")
                 .append("    A.PART_CHG, ")
                 .append("    A.ITEM_TYPE, ")
                 .append("    A.ITEM_SUBTYPE, ")
                 .append("    A.PROGRAM, ")
                 .append("    A.MFG_BOM_CHG, ")
                 .append("    A.MODEL, ")
                 .append("    A.PLAN_TITLE, ")
                 .append("    A.ORDER_UOM, ")
                 .append("    A.UNIT_TYPE, ")
                 .append("    A.PROJECT, ")
                 //.append("    ALT_ID, ")
                 //.append("    ALT_COUNT, ")
                 //.append("    ALT_STATUS, ")
                 //.append("    ALTER_TYPE, ")
                 .append("    A.ENG_PART_NO, ")
                 .append("    A.ENG_PART_CHG, ")
                 .append("    A.ENG_GROUP, ")
                 .append("    A.MFG_INDEX_NO, ")
                 .append("    A.PLG_GROUP, ")
                 .append("    A.LTA_SEND_FLAG, ")
                 .append("    A.OPER_SEQ_FLAG, ")
                 //.append("    UNSCRAP_FLAG, ")
                 //.append("    STATUS_CHG_REASON, ")
                 //.append("    STATUS_CHG_NOTES, ")
                 .append("    A.EXTERNAL_PLM_NO, ")
                 .append("    A.EXTERNAL_ERP_NO, ")
                 .append("    A.CONDITION, ")
                 .append("    A.BOM_NO, ")
                 .append("    A.UCF_PLAN_VCH1, ")
                 .append("    A.UCF_PLAN_VCH2, ")
                 .append("    A.UCF_PLAN_VCH3, ")
                 .append("    A.UCF_PLAN_VCH4, ")
                 .append("    A.UCF_PLAN_VCH5, ")
                 .append("    A.UCF_PLAN_VCH6, ")
                 .append("    A.UCF_PLAN_VCH7, ")
                 .append("    A.UCF_PLAN_VCH8, ")
                 .append("    A.UCF_PLAN_VCH9, ")
                 .append("    A.UCF_PLAN_VCH10, ")
                 .append("    A.UCF_PLAN_VCH11, ")
                 .append("    A.UCF_PLAN_VCH12, ")
                 .append("    A.UCF_PLAN_VCH13, ")
                 .append("    A.UCF_PLAN_VCH14, ")
                 .append("    A.UCF_PLAN_VCH15, ")
                 .append("    A.UCF_PLAN_VCH255_1, ")
                 .append("    A.UCF_PLAN_VCH255_2, ")
                 .append("    A.UCF_PLAN_VCH255_3, ")
                 .append("    A.UCF_PLAN_VCH4000_1, ")
                 .append("    A.UCF_PLAN_VCH4000_2, ")
                 .append("    A.UCF_PLAN_FLAG1, ")
                 .append("    A.UCF_PLAN_FLAG2, ")
                 .append("    A.UCF_PLAN_FLAG3, ")
                 .append("    A.UCF_PLAN_FLAG4, ")
                 .append("    A.UCF_PLAN_FLAG5, ")
                 .append("    A.UCF_PLAN_NUM1, ")
                 .append("    A.UCF_PLAN_NUM2, ")
                 .append("    A.UCF_PLAN_NUM3, ")
                 .append("    A.UCF_PLAN_NUM4, ")
                 .append("    A.UCF_PLAN_NUM5, ")
                 .append("    A.UCF_PLAN_DATE1, ")
                 .append("    A.UCF_PLAN_DATE2, ")
                 .append("    A.UCF_PLAN_DATE3, ")
                 .append("    A.UCF_PLAN_DATE4, ")
                 .append("    A.UCF_PLAN_DATE5, ")
                 .append("    A.UCF_ORDER_VCH1, ")
                 .append("    A.UCF_ORDER_VCH2, ")
                 .append("    A.UCF_ORDER_VCH3, ")
                 .append("    A.UCF_ORDER_VCH4, ")
                 .append("    A.UCF_ORDER_VCH5, ")
                 .append("    A.UCF_ORDER_VCH6, ")
                 .append("    A.UCF_ORDER_VCH7, ")
                 .append("    A.UCF_ORDER_VCH8, ")
                 .append("    A.UCF_ORDER_VCH9, ")
                 .append("    A.UCF_ORDER_VCH10, ")
                 .append("    A.UCF_ORDER_VCH11, ")
                 .append("    A.UCF_ORDER_VCH12, ")
                 .append("    A.UCF_ORDER_VCH13, ")
                 .append("    A.UCF_ORDER_VCH14, ")
                 .append("    A.UCF_ORDER_VCH15, ")
                 .append("    A.UCF_ORDER_VCH255_1, ")
                 .append("    A.UCF_ORDER_VCH255_2, ")
                 .append("    A.UCF_ORDER_VCH255_3, ")
                 .append("    A.UCF_ORDER_VCH4000_1, ")
                 .append("    A.UCF_ORDER_VCH4000_2, ")
                 .append("    A.UCF_ORDER_FLAG1, ")
                 .append("    A.UCF_ORDER_FLAG2, ")
                 .append("    A.UCF_ORDER_FLAG3, ")
                 .append("    A.UCF_ORDER_FLAG4, ")
                 .append("    A.UCF_ORDER_FLAG5, ")
                 .append("    A.UCF_ORDER_NUM1, ")
                 .append("    A.UCF_ORDER_NUM2, ")
                 .append("    A.UCF_ORDER_NUM3, ")
                 .append("    A.UCF_ORDER_NUM4, ")
                 .append("    A.UCF_ORDER_NUM5, ")
                 .append("    A.UCF_ORDER_DATE1, ")
                 .append("    A.UCF_ORDER_DATE2, ")
                 .append("    A.UCF_ORDER_DATE3, ")
                 .append("    A.UCF_ORDER_DATE4, ")
                 .append("    A.UCF_ORDER_DATE5, ")
                 .append("    A.DISPLAY_SEQUENCE, ")
                 .append("    A.SECURITY_GROUP ")
                 .append("    ,A.OPERATION_OVERLAP_FLAG ")
                 .append("FROM ")
                 .append("    SFWID_ORDER_DESC_ALT A, PWUST_SFWID_ORDER_DESC B")  //B is where PW_ORDER_NO is. Defect 880
                 .append("WHERE ")
                 .append("    A.ORDER_ID = ? AND ")
                 .append("    B.ORDER_ID = A.ORDER_ID AND ")
                 .append("    A.COMPLETE_ALT_ID = ? ");

		ParameterHolder params = new ParameterHolder();
		params.addParameter(orderId);
		params.addParameter(altId);
		
		return eds.queryForMap(selectSql.toString(), params);
	}
}