CREATE OR REPLACE FUNCTION UTASGI_FND_HAS_WORK_LOC_SECGRP(VI_USER_ID  VARCHAR2,
                                                          VI_WORK_LOC VARCHAR2)
  RETURN VARCHAR IS
  TEMP VARCHAR2(1);
BEGIN
  SELECT 'X'
    INTO TEMP
    FROM UTASGI_USER_SEC_GRP_XREF A, SFFND_USER_SEC_GRP B
   WHERE A.HR_LOC = VI_WORK_LOC
     AND B.USERID = VI_USER_ID
     AND A.SECURITY_GROUP = B.SECURITY_GROUP
     AND ROWNUM = 1;

  IF TEMP = 'X' THEN
    RETURN 'Y';
  END IF;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 'N';
END;
/