--VIS_CONV_COMMON_PHRASES_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_CONV_COMMON_PHRASES_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_CONV_PLAN_PROGRESS_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_CONV_PLAN_PROGRESS_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_CONV_WORKCENTER_MAP_ID
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_CONV_WORKCENTER_MAP_ID
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_LEGACY_OPERATION_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_LEGACY_OPERATION_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_LEGACY_PLAN_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_LEGACY_PLAN_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_LEGACY_SUBJECT_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_LEGACY_SUBJECT_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_LIB_GRAPHIC_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_LIB_GRAPHIC_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_LIB_STANDARD_TEXT_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_LIB_STANDARD_TEXT_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_OPER_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_OPER_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_PLAN_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_PLAN_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_STD_OPER_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_STD_OPER_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_STEP_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_STEP_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_SUBJ_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_SUBJ_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/

--VIS_SUB_NET_SEQ
BEGIN
  DECLARE
    NAME_ALREADY_USED EXCEPTION;
    PRAGMA EXCEPTION_INIT(NAME_ALREADY_USED, -955);
  BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE VIS_SUB_NET_SEQ
                       MINVALUE 1 MAXVALUE 9999999999999999999999999999
                       INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE';
  EXCEPTION
    WHEN NAME_ALREADY_USED THEN NULL;
  END;
END;
/
