
set define off
prompt ---------------------------------------;
prompt Executing ... PWUST_647E028D9AE10B21E05387971F0A2536.sql
prompt ---------------------------------------;
declare
v_folder_id sfcore_udv_folder.folder_id%type :='PWUST_550FF0D87F4141A0E05387971F0AD3EA';
v_udv_id sfcore_udv_lib.udv_id%type  :='PWUST_647E028D9AE10B21E05387971F0A2536';
v_udv_tag sfcore_udv_lib.udv_tag%type :='PWUST_OrderOperStdalnIM';
v_udv_type sfcore_udv_lib.udv_type%type  :='INPMTX';
v_udv_desc sfcore_udv_lib.udv_desc%type  :='defect 760;defect 831;defect 664,1162,1044';
v_state sfcore_udv_lib.state%type  :='';
v_load_ref sfcore_udv_lib.load_ref%type  :='';
v_tool_version sfcore_udv_lib.tool_version%type  :='2.4.4.0.20190207~2.4';
v_object_rev sfcore_udv_lib.object_rev%type  :='';
v_owner_group sfcore_udv_lib.owner_group%type  :='';
v_stype sfcore_udv_lib.stype%type  :='';
p1 clob :='object TCBScrollBox
  Left = 0
  Top = 0
  Width = 458
  Height = 311
  HelpContext = ''''
  AutoScroll = False
  DoubleBuffered = False
  ParentDoubleBuffered = False
  Caption = ''Insert Operations''
  TransactionType = ttCached
  IMSqlTransactionName = ''WidOperAltIns''
  IMSqlSourceName = ''OrderOperStdalnIMSel''
  IMScanAction = saIMAccept
  IMBatchCommit = True
  IMAllowHeaderChanges = False
  IMNoSelectionLoadsAll = etDefault
  IMFixedColCount = -1
  IMPopulateFromParams = True
  IMBeginExecSqlId = ''MFI_WID_EVENTSAFTERINSERTOPERATION''
  IMPopulateFromTransactionParams = True
  UdvControlType = uctInputMatrix
  RequireLogonExpression = ''False''
  IgnoreAuxParams = True
  ClearAuxParams = True
  AutoCancelTimeout = -1
  MultimediaRequired = mmNo
  MMPopulateForInsert = False
  AlignContents = acTop
  SizeToEndOfLine = False
  AutoRefresh = arDisabled
  MinWidth = 0
  MinHeight = 0
  MaxWidth = 0
  MaxHeight = 0
  UserAbort = etDefault
  ProgressMeter = etDefault
  AutoScrollbars = True
  DynamicFieldAttributes = True
  BottomMargin = -1
  object OrderOperStdalnIMSel: TSfSqlSource
    SelectOnUserConnection = True
    SelectSqlId = ''pwust_OrderOperStdalnIMSel''
    DeleteSqlId = ''OrderOperDeleteSql''
    ParamsSQLSourceName = ''@ToolScope,@ScriptParams,MFI_WID_OperStdalnIMScopeSell''
    PublishParams = True
    SelectedFields.Strings = (
      ''OPER_NO~4~Oper;No~N~N~N~Y~N~N~~~~~Default~N~~~''
      ''OPER_TITLE~15~Oper Title~N~N~N~N~N~N~~~~~Default~N~~~''
      ''OPER_TYPE~5~Oper;Type~N~N~N~N~N~N~~~~~Default~N~~~''
      ''OPER_OPT_FLAG~3~Opt;Oper?~N~N~N~False~N~N~~~~~Default~N~~~''
      
        ''AUTO_START_FLAG~3~Auto;Start?~N~N~N~False~OPERATION_OVERLAP_FLAG'' +
        '' = ''#39''Y''#39''~N~~~~~Default~N~~~''
      
        ''AUTO_COMPLETE_FLAG~4~Auto;Complete?~N~N~N~False~OPERATION_OVERLA'' +
        ''P_FLAG = ''#39''Y''#39''~N~~~~~Default~N~~~''
      ''OCCUR_RATE~3~Occur;Rate~N~N~N~N~True~N~~~~~Default~N~~~''
      ''PLND_MACHINE_NO~8~Machine;No~N~N~N~N~True~N~~~~~Default~N~~~''
      ''ASGND_WORK_LOC~6~Work;Location~N~N~N~True~N~N~~~~~Default~N~~~''
      
        ''ASGND_WORK_DEPT~5~Work;Department~N~N~N~True~N~N~~~~~Default~N~~'' +
        ''~''
      ''ASGND_WORK_CENTER~5~Work;Center~N~N~N~True~N~N~~~~~Default~N~~~''
      
        ''UNIT_PROCESSING~10~Unit;Processing~N~N~False~False~True~N~~~~~De'' +
        ''fault~N~~~''
      ''TEST_TYPE~5~Test Type~N~N~N~N~True~N~~~~~Default~N~~~''
      ''OSP_FLAG~2~OSP?~N~N~N~False~True~N~~~~~Default~N~~~''
      ''SUPPLIER_CODE~7~Supplier;Code~N~N~N~N~True~N~~~~~Default~N~~~''
      ''OSP_DAYS~3~OSP ;Days~N~N~N~N~True~N~~~~~Default~N~~~''
      
        ''OSP_COST_PER_UNIT~5~OSP Cost;Per Unit~N~N~N~N~True~N~~~~~Default'' +
        ''~N~~~''
      ''REWORK_FLAG~0~REWORK_FLAG~N~N~N~N~Y~N~~~~~Default~N~~~''
      
        ''UCF_PLAN_OPER_VCH1~0~UCF_PLAN_OPER_VCH1~N~N~False~N~True~N~~~~~D'' +
        ''efault~N~~~''
      
        ''UCF_PLAN_OPER_VCH2~10~UCF_PLAN_OPER_VCH3~N~N~False~N~True~N~~~~~'' +
        ''Default~N~~~''
      
        ''UCF_PLAN_OPER_VCH3~0~UCF_PLAN_OPER_VCH3~N~N~False~N~True~N~~~~~D'' +
        ''efault~N~~~''
      
        ''UCF_PLAN_OPER_VCH4~0~UCF_PLAN_OPER_VCH4~N~N~False~N~True~N~~~~~D'' +
        ''efault~N~~~''
      
        ''UCF_PLAN_OPER_VCH5~0~UCF_PLAN_OPER_VCH5~N~N~False~N~True~N~~~~~D'' +
        ''efault~N~~~''
      
        ''UCF_PLAN_OPER_NUM1~0~UCF_PLAN_OPER_NUM1~N~N~False~N~True~N~~~~~D'' +
        ''efault~N~~~''
      
        ''UCF_PLAN_OPER_NUM2~0~UCF_PLAN_OPER_NUM2~N~N~False~N~True~N~~~~~D'' +
        ''efault~N~~~''
      
        ''UCF_PLAN_OPER_FLAG1~0~UCF_PLAN_OPER_FLAG1~N~N~False~N~True~N~~~~'' +
        ''~Default~N~~~''
      
        ''UCF_PLAN_OPER_FLAG2~0~UCF_PLAN_OPER_FLAG2~N~N~False~N~True~N~~~~'' +
        ''~Default~N~~~''
      
        ''UCF_ORDER_OPER_VCH1~0~UCF_ORDER_OPER_VCH1~N~N~N~N~Y~N~~~~~Defaul'' +
        ''t~N~~~''
      
        ''UCF_ORDER_OPER_VCH2~10~SuperNet~N~N~N~N~ORDER_TYPE=''#39''REPAIR''#39''~N~~~'' +
        ''~~Default~N~~~''
      
        ''UCF_ORDER_OPER_VCH3~10~Sub Net~N~N~False~False~ORDER_TYPE=''#39''REPAI'' +
        ''R''#39''~N~~~~~Default~N~~~''
      
        ''UCF_ORDER_OPER_NUM1~0~UCF_ORDER_OPER_NUM1~N~N~N~N~Y~N~~~~~Defaul'' +
        ''t~N~~~''
      
        ''UCF_ORDER_OPER_NUM2~0~UCF_ORDER_OPER_NUM2~N~N~N~N~Y~N~~~~~Defaul'' +
        ''t~N~~~''
      
        ''UCF_ORDER_OPER_FLAG1~0~UCF_ORDER_OPER_FLAG1~N~N~N~N~Y~N~~~~~Defa'' +
        ''ult~N~~~''
      
        ''UCF_ORDER_OPER_DATE1~0~UCF_ORDER_OPER_DATE1~N~N~N~N~Y~N~~~~~Defa'' +
        ''ult~N~~~''
      ''OPER_KEY~0~OPER_KEY~N~N~N~N~Y~N~~~~~Default~N~~~''
      
        ''SEQ_STEPS_FLAG~5~Execute Steps;in Sequence?~N~N~False~False~Fals'' +
        ''e~N~~~~~Default~N~~~''
      
        ''OPER_CHANGE_LEVEL~6~Operation;Change Level~N~N~False~False~True~'' +
        ''N~~~~~Default~N~~~''
      
        ''ORIENTATION_FLAG~10~Orientation~N~N~False~False~False~N~~~~~Defa'' +
        ''ult~N~~~''
      
        ''CROSS_ORDER_FLAG~5~Cross Order?~N~N~False~False~False~N~~~~~Defa'' +
        ''ult~N~~~''
      
        ''MUST_ISSUE_PARTS_FLAG~0~Must Use Issued Parts?~N~N~False~False~F'' +
        ''alse~N~~~~~Default~N~~~''
      
        ''EXE_ORDER~0~Oper;Sequence No~N~N~False~DISPLAY_SEQUENCE=''#39''Executi'' +
        ''on Order''#39''~DISPLAY_SEQUENCE<>''#39''Execution Order''#39''~N~~~~~Default~N~~~''
      
        ''AUTO_CYCLE_FLAG~1~Auto Cycle?~N~N~False~False~True~N~~~~~Default'' +
        ''~N~~~''
      
        ''UNITS_PER_CYCLE~4~Units Per Cycle~N~N~False~False~True~N~~~~~Def'' +
        ''ault~N~~~''
      
        ''PRINT_LABEL~6~Print;Label~N~N~False~False~True~N~~~~~Default~N~~'' +
        ''~''
      
        ''NUMBER_OF_LABELS~6~Number of;Labels~N~N~False~False~True~N~~~~~D'' +
        ''efault~N~~~''
      
        ''REPORT_ID_DISP~10~Label Id~N~N~False~False~True~N~~~~~Default~N~'' +
        ''~~''
      
        ''RECONCILE_SCRAP~6~Reconcile;Scrap~N~N~False~False~True~N~~~~~Def'' +
        ''ault~N~~~''
      
        ''UNITS_PER_CYCLE_ACTUAL~4~Units Per Cycle;Actual~N~N~False~False~'' +
        ''True~N~~~~~Default~N~~~''
      ''REPORT_ID~0~Report Id~N~N~False~False~True~N~~~~~Default~N~~~'')
    SelectedFieldsEditControl.Strings = (
      ''PLAN_ASGND_WORK_LOC~Edit''
      ''MUST_ISSUE_PARTS_FLAG~CheckBox=1~0''
      ''CROSS_ORDER_FLAG~CheckBox=1~0''
      ''UCF_PLAN_OPER_VCH5~Edit''
      ''UCF_PLAN_OPER_NUM1~Edit''
      ''UCF_PLAN_OPER_NUM2~Edit''
      ''UCF_PLAN_OPER_FLAG1~Edit''
      ''UCF_PLAN_OPER_FLAG2~Edit''
      ''UCF_ORDER_OPER_VCH1~Edit''
      ''UCF_ORDER_OPER_NUM1~Edit''
      ''UCF_ORDER_OPER_NUM2~Edit''
      ''UCF_ORDER_OPER_DATE1~Edit''
      ''UCF_PLAN_OPER_VCH3~Edit''
      ''UCF_PLAN_OPER_VCH4~Edit''
      ''AUTO_START_FLAG~Edit''
      ''TEST_TYPE~Edit''
      ''OSP_FLAG~Edit''
      ''SUPPLIER_CODE~Edit''
      ''OSP_DAYS~Edit''
      ''OPER_KEY~Edit''
      ''ORIENTATION_FLAG~Edit''
      ''EXE_ORDER~Edit''
      ''UNITS_PER_CYCLE~Edit''
      ''PRINT_LABEL~Edit''
      ''NUMBER_OF_LABELS~Edit''
      ''UNITS_PER_CYCLE_ACTUAL~Edit''
      ''REPORT_ID~Edit''
      ''ASGND_WORK_LOC~Edit''
      ''ASGND_WORK_DEPT~Edit''
      ''UCF_ORDER_OPER_VCH2~Edit'')
    TestParamValues.Strings = (
      ''ORDER_ID=1''
      ''@TAG=Ins''
      ''OPER_KEY=1'')
    DataDefinitions.Strings = (
      ''OPER_NO''
      ''OPER_TITLE''
      ''OPER_TYPE''
      ''OPER_OPT_FLAG''
      ''AUTO_START_FLAG''
      ''AUTO_COMPLETE_FLAG''
      ''OCCUR_RATE''
      ''PLND_MACHINE_NO''
      ''ASGND_WORK_LOC''
      ''ASGND_WORK_DEPT''
      ''ASGND_WORK_CENTER''
      ''UNIT_PROCESSING''
      ''TEST_TYPE''
      ''OSP_FLAG''
      ''SUPPLIER_CODE''
      ''OSP_DAYS''
      ''OSP_COST_PER_UNIT''
      ''REWORK_FLAG''
      ''UCF_PLAN_OPER_VCH1''
      ''UCF_PLAN_OPER_VCH2''
      ''UCF_PLAN_OPER_VCH3''
      ''UCF_PLAN_OPER_VCH4''
      ''UCF_PLAN_OPER_VCH5''
      ''UCF_PLAN_OPER_NUM1''
      ''UCF_PLAN_OPER_NUM2''
      ''UCF_PLAN_OPER_FLAG1''
      ''UCF_PLAN_OPER_FLAG2''
      ''UCF_ORDER_OPER_VCH1''
      ''UCF_ORDER_OPER_VCH2''
      ''UCF_ORDER_OPER_VCH3''
      ''UCF_ORDER_OPER_NUM1''
      ''UCF_ORDER_OPER_NUM2''
      ''UCF_ORDER_OPER_FLAG1''
      ''UCF_ORDER_OPER_DATE1''
      ''OPER_KEY''
      ''SEQ_STEPS_FLAG''
      ''OPER_CHANGE_LEVEL''
      ''ORIENTATION_FLAG''
      ''CROSS_ORDER_FLAG''
      ''MUST_ISSUE_PARTS_FLAG''
      ''EXE_ORDER''
      ''AUTO_CYCLE_FLAG''
      ''UNITS_PER_CYCLE''
      ''PRINT_LABEL''
      ''NUMBER_OF_LABELS''
      ''REPORT_ID_DISP''
      ''RECONCILE_SCRAP''
      ''UNITS_PER_CYCLE_ACTUAL''
      ''REPORT_ID'')
    ConsolidatedQuery = False
  end
  object WidOperAltIns: TSfSqlTransaction
    InputFieldsSSL.Strings = (
      ''ORDER_ID''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' Hidden=True''
      '' Required=False''
      '' PersistManualValues=Y''
      ''OPER_TYPE''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      '' MaxLength=40''
      '' DependentFields=TEST_TYPE''
      
        '' DefaultValue=@GetParamSourceValue(OrderOperStdalnIMSel,''#39''OPER_TY'' +
        ''PE''#39'')''
      ''OPER_OPT_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=Y''
      '' DefaultValue=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''OPER_TITLE''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=255''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=True''
      '' PersistManualValues=Y''
      
        '' DefaultValue=@GetParamSourceValue(OrderOperStdalnIMSel,''#39''OPER_TI'' +
        ''TLE''#39'')''
      ''PLND_MACHINE_NO''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' MaxLength=30''
      '' PersistManualValues=Y''
      ''REWORK_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' DefaultValue=N''
      '' PersistManualValues=Y''
      ''OSP_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=Y''
      '' DefaultValue=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''SUPPLIER_CODE''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=40''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''OSP_DAYS''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' MaxLength=9''
      '' PersistManualValues=Y''
      ''OSP_COST_PER_UNIT''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' MaxLength=9''
      '' PersistManualValues=Y''
      ''AUTO_START_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=Y''
      '' DefaultValue=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''AUTO_COMPLETE_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=Y''
      '' DefaultValue=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''ASGND_WORK_LOC''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=40''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=True''
      
        '' DefaultValue=@GetParamSourceValue(MFI_WID_OperStdalnIMScopeSel,'' +
        #39''PLND_ASGND_WORK_LOC''#39'')''
      '' PersistManualValues=Y''
      ''ASGND_WORK_DEPT''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=30''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=True''
      '' PersistManualValues=Y''
      
        '' DefaultValue=@GetParamSourceValue(OrderOperStdalnIMSel,''#39''ASGND_W'' +
        ''ORK_DEPT''#39'')''
      ''ASGND_WORK_CENTER''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=30''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=True''
      '' PersistManualValues=Y''
      
        '' DefaultValue=@GetParamSourceValue(OrderOperStdalnIMSel,''#39''ASGND_W'' +
        ''ORK_CENTER''#39'')''
      ''OCCUR_RATE''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' MaxLength=4''
      '' DefaultValue=1''
      '' PersistManualValues=Y''
      ''TEST_TYPE''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=30''
      '' CharCase=Y''
      '' Hidden=OPER_TYPE_ROLE<>''#39''Test''#39
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_ORDER_OPER_VCH1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_ORDER_OPER_NUM1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      '' MaxLength=9''
      ''UCF_ORDER_OPER_DATE1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_ORDER_OPER_NUM2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      '' MaxLength=9''
      ''PLND_ASGND_WORK_LOC''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' Hidden=True''
      '' Required=False''
      '' PersistManualValues=Y''
      ''part_no''
      '' AuxField=Y''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''part_chg''
      '' AuxField=Y''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''OPER_NO''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=Y''
      '' Hidden=False''
      '' Required=True''
      '' MaxLength=10''
      '' PersistManualValues=Y''
      
        '' DefaultValue=@GetParamSourceValue(OrderOperStdalnIMSel,''#39''OPER_NO'' +
        #39'')''
      ''UCF_ORDER_OPER_VCH4''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH5''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH6''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH7''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH8''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH9''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH10''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH11''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH12''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH13''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH14''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH15''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_NUM3''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_NUM4''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_NUM5''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_DATE2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_DATE3''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_DATE4''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_DATE5''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_FLAG2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_FLAG3''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_FLAG4''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_FLAG5''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH255_1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH255_2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH255_3''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH4000_1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH4000_2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''SEQ_STEPS_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=0''
      '' CharCase=Y''
      '' DefaultValue=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''OPER_CHANGE_LEVEL''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      '' MaxLength=6''
      ''EXE_ORDER''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=DISPLAY_SEQUENCE<>''#39''Execution Order''#39
      '' Required=DISPLAY_SEQUENCE=''#39''Execution Order''#39
      '' MaxLength=9''
      ''ORIENTATION_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=12''
      '' CharCase=N''
      '' DefaultValue=Unit Centric''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''CROSS_ORDER_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' DefaultValue=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''MUST_ISSUE_PARTS_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' DefaultValue=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UNIT_PROCESSING''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=True''
      '' MaxLength=20''
      '' DefaultValue=Normal''
      ''UNITS_PER_CYCLE''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=UNIT_PROCESSING<>''#39''Cycle''#39
      '' Required=False''
      '' MaxLength=9''
      '' DefaultValue=1''
      ''AUTO_CYCLE_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=UNIT_PROCESSING<>''#39''Cycle''#39
      '' Required=False''
      '' MaxLength=1''
      '' DefaultValue=N''
      ''PRINT_LABEL''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      '' MaxLength=20''
      '' DefaultValue=Off''
      ''NUMBER_OF_LABELS''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      '' MaxLength=9''
      '' DefaultValue=1''
      ''REPORT_ID''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''RECONCILE_SCRAP''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=OPERATION_OVERLAP_FLAG<>''#39''Y''#39
      '' Required=False''
      '' DefaultValue=Off''
      ''UNITS_PER_CYCLE_ACTUAL''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=UNIT_PROCESSING<>''#39''Cycle''#39
      '' Required=False''
      '' MaxLength=9''
      '' DefaultValue=1''
      ''REPORT_ID_DISP''
      '' AuxField=Y''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''OPER_TYPE_ROLE''
      '' AuxField=Y''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' DependentFields=TEST_TYPE''
      '' PersistManualValues=Y''
      '' Hidden=True''
      '' Required=False''
      ''UCF_ORDER_OPER_VCH2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=ORDER_TYPE=''#39''REPAIR''#39
      '' Required=False''
      ''UCF_ORDER_OPER_VCH3''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=ORDER_TYPE=''#39''REPAIR''#39
      '' Required=False'')
    InputFieldsEditControlSSL.Strings = (
      ''PLND_MACHINE_NO''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_WID_MACHINE_NO_LKUP''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''REWORK_FLAG''
      '' CtrlType=Edit''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''OSP_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''OSP_DAYS''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=2''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''OSP_COST_PER_UNIT''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=2''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_NUM1''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_DATE1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_NUM2''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''part_no''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''part_chg''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH4''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH5''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH6''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH7''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH8''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH9''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH10''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH11''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH12''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH13''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH14''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH15''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_NUM3''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_NUM4''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_NUM5''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0';
p2 clob :='''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_DATE2''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_DATE3''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_DATE4''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_DATE5''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_FLAG2''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_FLAG3''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_FLAG4''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_FLAG5''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH255_1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH255_2''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH255_3''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH4000_1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ORDER_OPER_VCH4000_2''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''SEQ_STEPS_FLAG''
      '' CtrlType=List''
      ''  Values=N~Y''
      ''OPER_CHANGE_LEVEL''
      '' CtrlType=List''
      ''  Values=Major~Minor''
      ''ORIENTATION_FLAG''
      '' CtrlType=List''
      ''  Values=Unit Centric~Data Collection Centric''
      ''CROSS_ORDER_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''MUST_ISSUE_PARTS_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''PRINT_LABEL''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_FND_PrintLabelLookup''
      ''  Validate=Y''
      ''  DefaultToSingle=Y''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Short''
      ''   Static=N''
      ''UNITS_PER_CYCLE''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''AUTO_CYCLE_FLAG''
      '' CtrlType=List''
      ''  Values=N~Y''
      ''UNITS_PER_CYCLE_ACTUAL''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UNIT_PROCESSING''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_FND_MATERIALHANDLINGLOOKUP''
      ''  ParamsSrc=MFI_WID_OperStdalnIMScopeSel''
      ''  Validate=Y''
      ''  DefaultToSingle=Y''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Short''
      ''   Static=N''
      ''AUTO_START_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''OCCUR_RATE''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=2''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''NUMBER_OF_LABELS''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''PLND_ASGND_WORK_LOC''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''SUPPLIER_CODE''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_FND_SUPPLIER_LOOKUP''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''   SUPPLIER_CODE=Supplier Code(20)''
      ''   Supplier=Supplier Name(24)''
      ''   COMPANY=Company''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''RECONCILE_SCRAP''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_FND_RECONCILESCRAPLOOKUP''
      ''  Validate=Y''
      ''  DefaultToSingle=Y''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Short''
      ''   Static=N''
      ''REPORT_ID_DISP''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_FND_LabelReportLookup''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''   REPORT_ID_DISP=Report Id Disp''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''EXE_ORDER''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''AUTO_COMPLETE_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''REPORT_ID''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''OPER_TYPE_ROLE''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=AsIs''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''TEST_TYPE''
      '' CtrlType=Lookup''
      ''  SqlId=TestTypeLookup''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Short''
      ''   Static=N''
      ''UCF_ORDER_OPER_VCH2''
      '' CtrlType=Lookup''
      ''  Currency=N''
      ''  SqlId=PWUST_sel_sup_net_add_oper''
      ''  ParamsSrc=@toolscope''
      ''  Validate=Y''
      ''  DefaultToSingle=Y''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''UCF_ORDER_OPER_VCH3''
      '' CtrlType=Lookup''
      ''  Currency=N''
      ''  SqlId=PWUST_SEL_SUB_NET_ADD_OPER''
      ''  ParamsSrc=@toolscope''
      ''  Validate=Y''
      ''  DefaultToSingle=Y''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''OPER_TYPE''
      '' CtrlType=Lookup''
      ''  Currency=N''
      ''  SqlId=sfpl_oper_type_def''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''OPER_OPT_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''OPER_TITLE''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''OPER_NO''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''ORDER_ID''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''ASGND_WORK_LOC''
      '' CtrlType=Lookup''
      ''  Currency=N''
      ''  SqlId=widworkloc_lookup''
      ''  ParamsSrc=@ToolScope,@InputMatrixFieldValues''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''   asgnd_work_loc=Work Location(20)''
      ''   loc_title=Location Title(24)''
      ''   COMPANY=Company''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''ASGND_WORK_DEPT''
      '' CtrlType=Lookup''
      ''  Currency=N''
      ''  SqlId=widworkdept_lookup''
      ''  ParamsSrc=@ToolScope,@InputMatrixFieldValues''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''ASGND_WORK_CENTER''
      '' CtrlType=Lookup''
      ''  Currency=N''
      ''  SqlId=widworkcenter_lookup''
      ''  ParamsSrc=@ToolScope,@InputMatrixFieldValues''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''   asgnd_Work_Center=Work Center''
      ''   Center_Title=Work Center Title''
      ''   Unit_Processing=Unit Processing''
      ''   Orientation_Flag=Orientation Flag''
      ''   Cross_Order_Flag=Cross Order Flag''
      ''   Must_Issue_Parts_Flag=Must Issue Parts Flag''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords'')
    InsertSqlId = ''pwust_WidOperAltIns''
    ParamsSQLSourceName = 
      ''WidOperTypeSel,@ToolScope,MFI_WID_OperStdalnIMScopeSel,@ScriptPa'' +
      ''rams,MFI_WID_GetExecutionOrderFromColumnValue''
    RefreshParams = False
    RefreshedSQLSourceName = ''OrderOperStdalnIMSel''
    DataDefinitions.Strings = (
      ''ORDER_ID=''
      ''OPER_TYPE=''
      ''OPER_OPT_FLAG=''
      ''OPER_TITLE=''
      ''PLND_MACHINE_NO=''
      ''REWORK_FLAG=''
      ''OSP_FLAG=''
      ''SUPPLIER_CODE=''
      ''OSP_DAYS=''
      ''OSP_COST_PER_UNIT=''
      ''AUTO_START_FLAG=''
      ''AUTO_COMPLETE_FLAG=''
      ''ASGND_WORK_LOC=''
      ''ASGND_WORK_DEPT=''
      ''ASGND_WORK_CENTER=''
      ''OCCUR_RATE=''
      ''TEST_TYPE=''
      ''UCF_ORDER_OPER_VCH1=''
      ''UCF_ORDER_OPER_NUM1=''
      ''UCF_ORDER_OPER_DATE1=''
      ''UCF_ORDER_OPER_NUM2=''
      ''PLND_ASGND_WORK_LOC=''
      ''OPER_NO=''
      ''UCF_ORDER_OPER_VCH4=''
      ''UCF_ORDER_OPER_VCH5=''
      ''UCF_ORDER_OPER_VCH6=''
      ''UCF_ORDER_OPER_VCH7=''
      ''UCF_ORDER_OPER_VCH8=''
      ''UCF_ORDER_OPER_VCH9=''
      ''UCF_ORDER_OPER_VCH10=''
      ''UCF_ORDER_OPER_VCH11=''
      ''UCF_ORDER_OPER_VCH12=''
      ''UCF_ORDER_OPER_VCH13=''
      ''UCF_ORDER_OPER_VCH14=''
      ''UCF_ORDER_OPER_VCH15=''
      ''UCF_ORDER_OPER_NUM3=''
      ''UCF_ORDER_OPER_NUM4=''
      ''UCF_ORDER_OPER_NUM5=''
      ''UCF_ORDER_OPER_DATE2=''
      ''UCF_ORDER_OPER_DATE3=''
      ''UCF_ORDER_OPER_DATE4=''
      ''UCF_ORDER_OPER_DATE5=''
      ''UCF_ORDER_OPER_FLAG2=''
      ''UCF_ORDER_OPER_FLAG3=''
      ''UCF_ORDER_OPER_FLAG4=''
      ''UCF_ORDER_OPER_FLAG5=''
      ''UCF_ORDER_OPER_VCH255_1=''
      ''UCF_ORDER_OPER_VCH255_2=''
      ''UCF_ORDER_OPER_VCH255_3=''
      ''UCF_ORDER_OPER_VCH4000_1=''
      ''UCF_ORDER_OPER_VCH4000_2=''
      ''SEQ_STEPS_FLAG=''
      ''OPER_CHANGE_LEVEL=''
      ''EXE_ORDER=''
      ''ORIENTATION_FLAG=''
      ''CROSS_ORDER_FLAG=''
      ''MUST_ISSUE_PARTS_FLAG=''
      ''UNIT_PROCESSING=''
      ''UNITS_PER_CYCLE=''
      ''AUTO_CYCLE_FLAG=''
      ''PRINT_LABEL=''
      ''NUMBER_OF_LABELS=''
      ''REPORT_ID=''
      ''RECONCILE_SCRAP=''
      ''UNITS_PER_CYCLE_ACTUAL=''
      ''UCF_ORDER_OPER_VCH2=''
      ''UCF_ORDER_OPER_VCH3='')
  end
  object MFI_WID_OperStdalnIMScopeSel: TsfTransactionParamSource
    SelectSqlId = ''MFI_WID_OperStdalnIMScopeSel''
    ParamsSQLSourceName = ''@ToolScope,@ScriptParams''
    PublishParams = True
  end
  object MFI_WID_GetExecutionOrderFromColumnValue: TsfTransactionParamSource
    SelectSqlId = ''MFI_WID_GetExecutionOrderFromColumnValue''
    ParamsSQLSourceName = ''MFI_WID_OperStdalnIMScopeSel,@ToolScope,@ScriptParams''
    PublishParams = True
  end
  object WidOperTypeSel: TsfTransactionParamSource
    SelectSqlId = ''MFI_WID_OperTypeSel''
    ParamsSQLSourceName = ''OrderOperStdalnIMSel''
    PublishParams = True
  end
end';
v_iclob clob;
begin
v_iclob := p1||p2;
begin
  insert into sfcore_udv_lib(udv_id,udv_tag,updt_userid,time_stamp,udv_type,stype,udv_desc,state,load_ref,tool_version,object_rev,owner_group,udv_definition)
    values(v_udv_id,v_udv_tag,user,sysdate,v_udv_type,v_stype,v_udv_desc,v_state,v_load_ref,v_tool_version,v_object_rev,v_owner_group,
    replace(replace(v_iclob,chr(39)||chr(39)||chr(39),chr(39)||chr(39)),'POUND39_HOLDER',chr(35)||chr(51)||chr(57)));
  commit;
exception when dup_val_on_index then
  begin
    update sfcore_udv_lib
    set udv_definition=replace(replace(v_iclob,chr(39)||chr(39)||chr(39),chr(39)||chr(39)),'POUND39_HOLDER',chr(35)||chr(51)||chr(57)),updt_userid=user,time_stamp=sysdate,
      tool_version=v_tool_version,udv_tag=v_udv_tag,udv_desc = v_udv_desc,state=v_state,object_rev=v_object_rev,owner_group=v_owner_group,
      udv_type=v_udv_type,stype=v_stype
    where udv_id=v_udv_id;
    commit;
  exception when others then
  	 sffnd_show_execution_message('DML',v_udv_id, SQLCODE,SQLERRM,' update sfcore_udv_lib ');
  end;
when others then
  sffnd_show_execution_message('DML',v_udv_id, SQLCODE,SQLERRM,' insert into sfcore_udv_lib ');
end;
begin
 if v_folder_id is not null then
  insert into sfcore_udv_folder(udv_id,folder_id,updt_userid,time_stamp)
  values(v_udv_id,v_folder_id,user,sysdate);
  commit;
 end if;
exception when others then 
 sffnd_show_execution_message('DML',v_udv_id, SQLCODE,SQLERRM,' insert into sfcore_udv_folder ');
end;
end;
/

set define on

