
set define off
prompt ---------------------------------------;
prompt Executing ... PWUST_57E79DA2EF610E4BE05387971F0A0D8C.sql
prompt ---------------------------------------;
declare
v_folder_id sfcore_udv_folder.folder_id%type :='PWUST_550FF0D87F4141A0E05387971F0AD3EA';
v_udv_id sfcore_udv_lib.udv_id%type  :='PWUST_57E79DA2EF610E4BE05387971F0A0D8C';
v_udv_tag sfcore_udv_lib.udv_tag%type :='PWUST_PartListUpd';
v_udv_type sfcore_udv_lib.udv_type%type  :='INPUT';
v_udv_desc sfcore_udv_lib.udv_desc%type  :='';
v_state sfcore_udv_lib.state%type  :='';
v_load_ref sfcore_udv_lib.load_ref%type  :='';
v_tool_version sfcore_udv_lib.tool_version%type  :='2.3.1.8.20170110~2.3';
v_object_rev sfcore_udv_lib.object_rev%type  :='';
v_owner_group sfcore_udv_lib.owner_group%type  :='';
v_stype sfcore_udv_lib.stype%type  :='';
p1 clob :='object TCBScrollBox
  Left = 0
  Top = 0
  Width = 800
  Height = 800
  AutoScroll = False
  Caption = ''Update Part''
  ConfirmationMsg = 
    ''Changing the SERIAL/LOT flag will remove the related BOM''#39''s SERIA'' +
    ''L/LOT effectivities. Are you sure, you want to continue?''
  ConfirmationMsgExpr = 
    ''@TransactionType = ''#39''Update''#39'' AND (SERIAL_BOM_EFFECTIVITY_EXISTS ='' +
    '' ''#39''Y''#39'' AND WO_SERIAL_FLAG = ''#39''N''#39'') OR (LOT_BOM_EFFECTIVITY_EXISTS = '' +
    #39''Y''#39'' AND WO_LOT_FLAG = ''#39''N''#39'')''
  IMScanAction = saIMAccept
  IMAllowHeaderChanges = False
  IMNoSelectionLoadsAll = etDefault
  IMFixedColCount = -1
  IMPopulateFromParams = False
  UdvControlType = uctSingle
  RequireLogonExpression = ''False''
  AutoCancelTimeout = -1
  MultimediaRequired = mmNo
  MMPopulateForInsert = False
  AlignContents = acTop
  SizeToEndOfLine = False
  AutoRefresh = arRefreshAndFilter
  MinWidth = 0
  MinHeight = 0
  MaxWidth = 0
  MaxHeight = 0
  UserAbort = etDefault
  ProgressMeter = etDefault
  AutoScrollbars = True
  DynamicFieldAttributes = True
  BottomMargin = -1
  object _OBJ1: TsfDBInputEdit
    Left = 85
    Top = 21
    Width = 163
    Height = 25
    EmptyTextStyle = []
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = ''Tahoma''
    Font.Style = []
    ParentFont = True
    ShowHint = False
    TabOrder = 0
    EntryType = etAlphaNumeric
    Caption = ''Part No*''
    CaptionPos = cpLeft
    CaptionFont.Charset = DEFAULT_CHARSET
    CaptionFont.Color = clBlue
    CaptionFont.Height = -11
    CaptionFont.Name = ''Tahoma''
    CaptionFont.Style = []
    Hidden = False
    EnterForOkay = False
  end
  object _OBJ2: TsfDBInputEdit
    Left = 312
    Top = 21
    Width = 58
    Height = 25
    EmptyTextStyle = []
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = ''Tahoma''
    Font.Style = []
    ParentFont = True
    ShowHint = False
    TabOrder = 1
    EntryType = etAlphaNumeric
    Caption = ''Part Rev*''
    CaptionPos = cpLeft
    CaptionFont.Charset = DEFAULT_CHARSET
    CaptionFont.Color = clBlue
    CaptionFont.Height = -11
    CaptionFont.Name = ''Tahoma''
    CaptionFont.Style = []
    Hidden = False
    EnterForOkay = False
  end
  object _OBJ3: TsfDBInputEdit
    Left = 456
    Top = 56
    Width = 58
    Height = 25
    EmptyTextStyle = []
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = ''Tahoma''
    Font.Style = []
    ParentFont = True
    ShowHint = False
    TabOrder = 2
    EntryType = etAlphaNumeric
    Caption = ''Item Type''
    CaptionPos = cpLeft
    CaptionFont.Charset = DEFAULT_CHARSET
    CaptionFont.Color = clBlack
    CaptionFont.Height = -11
    CaptionFont.Name = ''Tahoma''
    CaptionFont.Style = []
    Hidden = False
    EnterForOkay = False
  end
  object TRACKABLE: TsfDBInputEdit
    Left = 85
    Top = 59
    Width = 285
    Height = 25
    EmptyTextStyle = []
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = ''Tahoma''
    Font.Style = []
    ParentFont = True
    ShowHint = False
    TabOrder = 5
    EntryType = etAlphaNumeric
    Caption = ''Title*''
    CaptionPos = cpLeft
    CaptionFont.Charset = DEFAULT_CHARSET
    CaptionFont.Color = clBlue
    CaptionFont.Height = -11
    CaptionFont.Name = ''Tahoma''
    CaptionFont.Style = []
    Hidden = False
    EnterForOkay = False
  end
  object _OBJ6: TsfDBInputEdit
    Left = 250
    Top = 129
    Width = 163
    Height = 25
    EmptyTextStyle = []
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = ''Tahoma''
    Font.Style = []
    ParentFont = True
    ShowHint = False
    TabOrder = 3
    EntryType = etAlphaNumeric
    Caption = ''UOM*''
    CaptionPos = cpLeft
    CaptionFont.Charset = DEFAULT_CHARSET
    CaptionFont.Color = clBlue
    CaptionFont.Height = -11
    CaptionFont.Name = ''Tahoma''
    CaptionFont.Style = []
    Hidden = False
    EnterForOkay = False
  end
  object _OBJ14: TsfDBInputEdit
    Left = 454
    Top = 88
    Width = 133
    Height = 25
    EmptyTextStyle = []
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = ''Tahoma''
    Font.Style = []
    ParentFont = True
    ShowHint = False
    TabOrder = 6
    EntryType = etAlphaNumeric
    Caption = ''UCF;ITEM VCH1''
    CaptionPos = cpLeft
    CaptionFont.Charset = DEFAULT_CHARSET
    CaptionFont.Color = clBlack
    CaptionFont.Height = -11
    CaptionFont.Name = ''Tahoma''
    CaptionFont.Style = []
    Hidden = False
    EnterForOkay = False
  end
  object ItemSubtype: TsfDBInputEdit
    Left = 455
    Top = 21
    Width = 129
    Height = 25
    EmptyTextStyle = []
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = ''Tahoma''
    Font.Style = []
    ParentFont = True
    ShowHint = False
    TabOrder = 4
    EntryType = etAlphaNumeric
    Caption = ''Part;Subtype''
    CaptionPos = cpLeft
    CaptionFont.Charset = DEFAULT_CHARSET
    CaptionFont.Color = clBlack
    CaptionFont.Height = -11
    CaptionFont.Name = ''Tahoma''
    CaptionFont.Style = []
    Hidden = False
    EnterForOkay = False
  end
  object _OBJ69: TsfDBInputEdit
    Left = 90
    Top = 122
    Width = 121
    Height = 25
    EmptyTextStyle = []
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = ''Tahoma''
    Font.Style = []
    ParentFont = True
    ShowHint = False
    TabOrder = 7
    EntryType = etAlphaNumeric
    Caption = ''ITEM_ID''
    CaptionPos = cpLeft
    CaptionFont.Charset = DEFAULT_CHARSET
    CaptionFont.Color = clWindowText
    CaptionFont.Height = -11
    CaptionFont.Name = ''Tahoma''
    CaptionFont.Style = []
    Hidden = False
    EnterForOkay = False
  end
  object ItemListUpd: TsfSqlTransaction
    InputFieldsSSL.Strings = (
      ''ITEM_ID''
      '' Update=False''
      '' Insert=True''
      '' PopulateForInsert=Y''
      '' MaxLength=0''
      '' CharCase=N''
      '' Hidden=True''
      '' Required=False''
      '' PersistManualValues=Y''
      ''PART_NO''
      '' Update=Y''
      '' Insert=N''
      '' PopulateForInsert=N''
      '' MaxLength=40''
      '' CharCase=Y''
      '' Hidden=N''
      '' Required=N''
      ''PART_CHG''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=Y''
      '' MaxLength=10''
      '' CharCase=Y''
      '' Hidden=True''
      '' Required=False''
      '' PersistManualValues=N''
      '' DefaultValue=N/A''
      ''PROGRAM''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' MaxLength=30''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''PART_TITLE''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' MaxLength=255''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''STOCK_UOM''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' MaxLength=10''
      '' CharCase=N''
      '' Hidden=True''
      '' Required=False''
      '' PersistManualValues=Y''
      '' DefaultValue=EA''
      ''EXP_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' MaxLength=1''
      '' CharCase=Y''
      '' DefaultValue=N''
      '' Hidden=N''
      '' Required=N''
      ''SPOOL_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' MaxLength=1''
      '' CharCase=Y''
      '' DefaultValue=N''
      '' Hidden=N''
      '' Required=N''
      ''PARENT_ENG_PART_NO''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=50''
      '' CharCase=Y''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_ITEM_VCH1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' MaxLength=50''
      '' CharCase=N''
      '' Hidden=True''
      '' Required=False''
      '' DefaultValue=ADDED IN SOLUMINA''
      '' PersistManualValues=Y''
      ''UCF_ITEM_VCH2''
      '' Update=N''
      '' Insert=N''
      '' PopulateForInsert=N''
      '' MaxLength=50''
      '' CharCase=N''
      '' Hidden=Y''
      '' Required=N''
      ''UCF_ITEM_NUM1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=0''
      '' CharCase=N''
      '' Hidden=True''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_ITEM_FLAG1''
      '' Update=N''
      '' Insert=N''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=N''
      '' Hidden=Y''
      '' Required=N''
      ''WORK_LOC''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''WO_SERIAL_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=Y''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''WO_LOT_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=Y''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''COMP_SERIAL_FLAG''
      '' Update=N''
      '' Insert=N''
      '' PopulateForInsert=N''
      '' CharCase=Y''
      '' Hidden=N''
      '' Required=N''
      ''COMP_LOT_FLAG''
      '' Update=N''
      '' Insert=N''
      '' PopulateForInsert=N''
      '' CharCase=Y''
      '' Hidden=N''
      '' Required=N''
      ''OPT_DC1_FLAG''
      '' Update=N''
      '' Insert=N''
      '' PopulateForInsert=N''
      '' CharCase=Y''
      '' Hidden=Y''
      '' Required=N''
      ''OPT_DC2_FLAG''
      '' Update=N''
      '' Insert=N''
      '' PopulateForInsert=N''
      '' CharCase=Y''
      '' Hidden=Y''
      '' Required=N''
      ''OPT_DC3_FLAG''
      '' Update=N''
      '' Insert=N''
      '' PopulateForInsert=N''
      '' CharCase=Y''
      '' Hidden=Y''
      '' Required=N''
      ''OPT_DC4_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=Y''
      '' Hidden=True''
      '' Required=False''
      '' PersistManualValues=Y''
      ''OBSOLETE_RECORD_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=Y''
      '' Hidden=N''
      '' Required=N''
      '' MaxLength=1''
      '' DefaultValue=N''
      ''PARENT_ENG_PART_CHG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=10''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''STANDARD_PART_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=Y''
      '' DefaultValue=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_ITEM_VCH3''
      ''UCF_ITEM_VCH4''
      ''UCF_ITEM_VCH5''
      ''UCF_ITEM_VCH6''
      ''UCF_ITEM_VCH7''
      ''UCF_ITEM_VCH8''
      ''UCF_ITEM_VCH9''
      ''UCF_ITEM_VCH10''
      ''UCF_ITEM_VCH11''
      ''UCF_ITEM_VCH12''
      ''UCF_ITEM_VCH13''
      ''UCF_ITEM_VCH14''
      ''UCF_ITEM_VCH15''
      ''UCF_ITEM_NUM2''
      ''UCF_ITEM_NUM3''
      ''UCF_ITEM_NUM4''
      ''UCF_ITEM_NUM5''
      ''UCF_ITEM_FLAG2''
      ''UCF_ITEM_FLAG3''
      ''UCF_ITEM_FLAG4''
      ''UCF_ITEM_FLAG5''
      ''UCF_ITEM_DATE1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ITEM_DATE2''
      ''UCF_ITEM_DATE3''
      ''UCF_ITEM_DATE4''
      ''UCF_ITEM_DATE5''
      ''FLIGHT_SAFETY_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''FLIGHT_ESSENTIAL_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''SOURCE_INSP_PLAN_ID''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=True''
      '' Required=False''
      ''DEST_INSP_PLAN_ID''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=True''
      '' Required=False''
      ''SOURCE_INSP_PLAN_REV''
      '' AuxField=Y''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''DEST_INSP_PLAN_REV''
      '' AuxField=Y''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''SOURCE_INSP_PLAN_NO''
      '' AuxField=Y''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''DEST_INSP_PLAN_NO''
      '' AuxField=Y''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UTILIZATION_RULE''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' DefaultValue=Any''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''TRACKABLE_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UID_ENTRY_NAME''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UID_ACQUISITION_CODE''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UID_ITEM_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' DefaultValue=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''ITEM_TYPE''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=Y''
      '' MaxLength=10''
      '' CharCase=Y''
      '' PersistManualValues=Y''
      '' Hidden=True''
      '' Required=False''
      ''ITEM_SUBTYPE''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      '' MaxLength=10''
      ''FLIGHT_DAYS''
      ''FLIGHT_HOURS''
      ''FLIGHT_CYCLES''
      ''STD_COST''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=10''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''TOOL_CALIBRATE_DAYS''
      ''TOOL_CALIBRATE_HOURS''
      ''TOOL_CALIBRATE_USES''
      ''TOOL_CALIBRATION_DAYS_FREQ''
      ''TOOL_CALIBRATION_HOURS_FREQ''
      ''TOOL_CALIBRATION_USES_FREQ''
      ''PHANTOM_KIT_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=N''
      '' DefaultValue=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''MFG_INSP_PLAN_NO''
      '' AuxField=Y''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''MFG_INSP_PLAN_REV''
      '' AuxField=Y''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''MFG_INSP_PLAN_ID''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=True''
      '' Required=False''
      ''SERIAL_NUM_GEN''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_ITEM_VCH255_1''
      ''UCF_ITEM_VCH255_2''
      ''UCF_ITEM_VCH255_3''
      ''UCF_ITEM_VCH4000_1''
      ''UCF_ITEM_VCH4000_2''
      ''UCF_ITEM_PROG_DETAIL_VCH1''
      ''UCF_ITEM_PROG_DETAIL_VCH2''
      ''UCF_ITEM_PROG_DETAIL_VCH3''
      ''UCF_ITEM_PROG_DETAIL_VCH4''
      ''UCF_ITEM_PROG_DETAIL_VCH5''
      ''UCF_ITEM_PROG_DETAIL_VCH6''
      ''UCF_ITEM_PROG_DETAIL_VCH7''
      ''UCF_ITEM_PROG_DETAIL_VCH8''
      ''UCF_ITEM_PROG_DETAIL_VCH9''
      ''UCF_ITEM_PROG_DETAIL_VCH10''
      ''UCF_ITEM_PROG_DETAIL_VCH11''
      ''UCF_ITEM_PROG_DETAIL_VCH12''
      ''UCF_ITEM_PROG_DETAIL_VCH13''
      ''UCF_ITEM_PROG_DETAIL_VCH14''
      ''UCF_ITEM_PROG_DETAIL_VCH15''
      ''UCF_ITEM_PROG_DETAIL_NUM1''
      ''UCF_ITEM_PROG_DETAIL_NUM2''
      ''UCF_ITEM_PROG_DETAIL_NUM3''
      ''UCF_ITEM_PROG_DETAIL_NUM4''
      ''UCF_ITEM_PROG_DETAIL_NUM5''
      ''UCF_ITEM_PROG_DETAIL_FLAG1''
      ''UCF_ITEM_PROG_DETAIL_FLAG2''
      ''UCF_ITEM_PROG_DETAIL_FLAG3''
      ''UCF_ITEM_PROG_DETAIL_FLAG4''
      ''UCF_ITEM_PROG_DETAIL_FLAG5''
      ''UCF_ITEM_PROG_DETAIL_DATE1''
      ''UCF_ITEM_PROG_DETAIL_DATE2''
      ''UCF_ITEM_PROG_DETAIL_DATE3''
      ''UCF_ITEM_PROG_DETAIL_DATE4''
      ''UCF_ITEM_PROG_DETAIL_DATE5''
      ''UCF_ITEM_PROG_DETAIL_VCH255_1''
      ''UCF_ITEM_PROG_DETAIL_VCH255_2''
      ''UCF_ITEM_PROG_DETAIL_VCH255_3''
      ''UCF_ITEM_PROG_DETAIL_VCH4000_1''
      ''UCF_ITEM_PROG_DETAIL_VCH4000_2''
      ''BUY_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''MAKE_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''AVG_PURCHASE_PRICE_PER_UNIT''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' MaxLength=22''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=BUY_FLAG<>''#39''Y''#39
      '' Required=BUY_FLAG=''#39''Y''#39
      ''AVG_MATERIAL_COST_PER_UNIT''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=MAKE_FLAG<>''#39''Y''#39
      '' Required=MAKE_FLAG=''#39''Y''#39
      '' MaxLength=22''
      ''AVG_LABOR_COST_PER_UNIT''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Required=MAKE_FLAG=''#39''Y''#39
      '' Hidden=MAKE_FLAG<>''#39''Y''#39
      '' MaxLength=22''
      ''PRICE_COST_UNIT''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''AVG_ORDER_LEAD_TIME_DAYS''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''COMMODITY_JURISDICTION''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=50''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''COMMODITY_CLASSIFICATION''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=50''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''ASSOCIATE_CHANGE''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' DefaultValue=N''
      '' PersistManualValues=Y''
      '' Hidden=CHANGE_REQUEST_ID<>''#39#39
      '' Required=False''
      ''@TRANSACTIONTYPE'')
    InputFieldsEditControlSSL.Strings = (
      ''PART_NO''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Format=1''
      ''  Decimal=0''
      ''  Currency=N''
      ''COMP_SERIAL_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''COMP_LOT_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''UCF_ITEM_VCH2''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''UCF_ITEM_FLAG1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''OPT_DC1_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''OPT_DC2_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''OPT_DC3_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''EXP_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''SPOOL_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''OBSOLETE_RECORD_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''SOURCE_INSP_PLAN_ID''
      '' CtrlType=Edit''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''DEST_INSP_PLAN_ID''
      '' CtrlType=Edit''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''WO_SERIAL_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''WO_LOT_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''FLIGHT_SAFETY_FLAG''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''FLIGHT_ESSENTIAL_FLAG''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''TRACKABLE_FLAG''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UTILIZATION_RULE''
      '' CtrlType=List''
      ''  Values=Any~Unit~Contract''
      ''UID_ACQUISITION_CODE''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_FND_UidAcquisitionCodeLkup''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  IMLookupFilter=N''
      ''  Style=Short''
      ''   Static=N''
      ''PART_TITLE''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UID_ENTRY_NAME''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_FND_UidEntryLkup''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  IMLookupFilter=N''
      ''  VisibleFields''
      ''   UID_ENTRY_NAME=UID Entry Name''
      ''   UID_ENTRY_DESC=UID Entry Desc''
      ''   CONSTRUCT_TYPE=Construct Type''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''PARENT_ENG_PART_CHG''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''PHANTOM_KIT_FLAG''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''SOURCE_INSP_PLAN_NO''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_SQA_SOURCE_INSP_PLAN_SELECT''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''   SOURCE_INSP_PLAN_NO=Source Insp Plan No''
      ''   SOURCE_INSP_PLAN_REV=Source Insp Plan Rev''
      ''   STATUS=Status''
      ''   DATE_CREATED=Date Created''
      ''   SOURCE_INSP_PLAN_TITLE=Source Insp Plan Title''
      ''   NOTES=Notes''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''DEST_INSP_PLAN_NO''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_SQA_DEST_INSP_PLAN_SELECT''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''   DEST_INSP_PLAN_NO=Dest Insp Plan No''
      ''   DEST_INSP_PLAN_REV=Dest Insp Plan Rev''
      ''   STATUS=Status''
      ''   DATE_CREATED=Date Created''
      ''   DEST_INSP_PLAN_TITLE=Dest Insp Plan Title''
      ''   NOTES=Notes''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''DEST_INSP_PLAN_REV''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''SOURCE_INSP_PLAN_REV''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''MFG_INSP_PLAN_REV''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''MFG_INSP_PLAN_NO''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_SQA_MFG_INSP_PLAN_SELECT''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''   MFG_INSP_PLAN_NO=Manufacturing Insp Plan No''
      ''   MFG_INSP_PLAN_REV=Manufacturing Insp Plan Rev''
      ''   STATUS=Status''
      ''   DATE_CREATED=Date Created''
      ''   MFG_INSP_PLAN_TITLE=Manufacturing Insp Plan Title''
      ''   NOTES=Notes''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''MFG_INSP_PLAN_ID''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''SERIAL_NUM_GEN''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_SELECTSERIALNOGENERATORLIST''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''MAKE_FLAG''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''BUY_FLAG''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''OPT_DC4_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''AVG_ORDER_LEAD_TIME_DAYS''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''PRICE_COST_UNIT''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''AVG_MATERIAL_COST_PER_UNIT''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''AVG_PURCHASE_PRICE_PER_UNIT''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ITEM_DATE1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''AVG_LABOR_COST_PER_UNIT''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''WORK_LOC''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''PARENT_ENG_PART_NO''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Format=1''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''STD_COST''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=2''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''STANDARD_PART_FLAG''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''UCF_ITEM_NUM1''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''ASSOCIATE_CHANGE''
      '' CtrlType=List''
      ''  Values=Y~N''
      ''COMMODITY_JURISDICTION''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=AsIs''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''COMMODITY_CL';
p2 clob :='ASSIFICATION''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=AsIs''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''PROGRAM''
      '' CtrlType=Lookup''
      ''  SqlId=Pl_ProgramDefSel''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''UID_ITEM_FLAG''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_FND_UidItemFlagLkup''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Short''
      ''   Static=N''
      ''ITEM_SUBTYPE''
      '' CtrlType=Edit''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=AsIs''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''STOCK_UOM''
      '' CtrlType=Lookup''
      ''  SqlId=UOMLookup''
      ''  Validate=Y''
      ''  DefaultToSingle=N''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Long''
      ''   FilterDefaults''
      ''    FilterCase=N''
      ''    PartialWordMatch=Y''
      ''    FindMultipleWords=Y''
      ''    DelimitedBy=,''
      ''    SearchType=stAnyWords''
      ''PART_CHG''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Format=1''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''ITEM_TYPE''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''ITEM_ID''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_ITEM_VCH1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N'')
    UpdateSqlId = ''ItemListUpd''
    ParamsSQLSourceName = ''@ToolScope''
    RefreshParams = False
    LinkedControls.Strings = (
      ''_OBJ2~PART_CHG''
      ''_OBJ1~PART_NO''
      ''_OBJ6~STOCK_UOM''
      ''TRACKABLE~PART_TITLE''
      ''_OBJ3~ITEM_TYPE''
      ''_OBJ14~UCF_ITEM_VCH1''
      ''ItemSubtype~ITEM_SUBTYPE''
      ''_OBJ69~ITEM_ID'')
    DataDefinitions.Strings = (
      ''ITEM_ID=''
      ''PART_NO=''
      ''PART_CHG=''
      ''PROGRAM=''
      ''PART_TITLE=''
      ''STOCK_UOM=''
      ''EXP_FLAG=''
      ''SPOOL_FLAG=''
      ''PARENT_ENG_PART_NO=''
      ''UCF_ITEM_VCH1=''
      ''UCF_ITEM_VCH2=''
      ''UCF_ITEM_NUM1=''
      ''UCF_ITEM_FLAG1=''
      ''WORK_LOC=''
      ''WO_SERIAL_FLAG=''
      ''WO_LOT_FLAG=''
      ''COMP_SERIAL_FLAG=''
      ''COMP_LOT_FLAG=''
      ''OPT_DC1_FLAG=''
      ''OPT_DC2_FLAG=''
      ''OPT_DC3_FLAG=''
      ''OPT_DC4_FLAG=''
      ''OBSOLETE_RECORD_FLAG=''
      ''PARENT_ENG_PART_CHG=''
      ''STANDARD_PART_FLAG=''
      ''UCF_ITEM_VCH3''
      ''UCF_ITEM_VCH4''
      ''UCF_ITEM_VCH5''
      ''UCF_ITEM_VCH6''
      ''UCF_ITEM_VCH7''
      ''UCF_ITEM_VCH8''
      ''UCF_ITEM_VCH9''
      ''UCF_ITEM_VCH10''
      ''UCF_ITEM_VCH11''
      ''UCF_ITEM_VCH12''
      ''UCF_ITEM_VCH13''
      ''UCF_ITEM_VCH14''
      ''UCF_ITEM_VCH15''
      ''UCF_ITEM_NUM2''
      ''UCF_ITEM_NUM3''
      ''UCF_ITEM_NUM4''
      ''UCF_ITEM_NUM5''
      ''UCF_ITEM_FLAG2''
      ''UCF_ITEM_FLAG3''
      ''UCF_ITEM_FLAG4''
      ''UCF_ITEM_FLAG5''
      ''UCF_ITEM_DATE1=''
      ''UCF_ITEM_DATE2''
      ''UCF_ITEM_DATE3''
      ''UCF_ITEM_DATE4''
      ''UCF_ITEM_DATE5''
      ''FLIGHT_SAFETY_FLAG=''
      ''FLIGHT_ESSENTIAL_FLAG=''
      ''SOURCE_INSP_PLAN_ID=''
      ''DEST_INSP_PLAN_ID=''
      ''UTILIZATION_RULE=''
      ''TRACKABLE_FLAG=''
      ''UID_ENTRY_NAME=''
      ''UID_ACQUISITION_CODE=''
      ''UID_ITEM_FLAG=''
      ''ITEM_TYPE=''
      ''ITEM_SUBTYPE=''
      ''FLIGHT_DAYS''
      ''FLIGHT_HOURS''
      ''FLIGHT_CYCLES''
      ''STD_COST=''
      ''TOOL_CALIBRATE_DAYS''
      ''TOOL_CALIBRATE_HOURS''
      ''TOOL_CALIBRATE_USES''
      ''TOOL_CALIBRATION_DAYS_FREQ''
      ''TOOL_CALIBRATION_HOURS_FREQ''
      ''TOOL_CALIBRATION_USES_FREQ''
      ''PHANTOM_KIT_FLAG=''
      ''MFG_INSP_PLAN_ID=''
      ''SERIAL_NUM_GEN=''
      ''UCF_ITEM_VCH255_1''
      ''UCF_ITEM_VCH255_2''
      ''UCF_ITEM_VCH255_3''
      ''UCF_ITEM_VCH4000_1''
      ''UCF_ITEM_VCH4000_2''
      ''UCF_ITEM_PROG_DETAIL_VCH1''
      ''UCF_ITEM_PROG_DETAIL_VCH2''
      ''UCF_ITEM_PROG_DETAIL_VCH3''
      ''UCF_ITEM_PROG_DETAIL_VCH4''
      ''UCF_ITEM_PROG_DETAIL_VCH5''
      ''UCF_ITEM_PROG_DETAIL_VCH6''
      ''UCF_ITEM_PROG_DETAIL_VCH7''
      ''UCF_ITEM_PROG_DETAIL_VCH8''
      ''UCF_ITEM_PROG_DETAIL_VCH9''
      ''UCF_ITEM_PROG_DETAIL_VCH10''
      ''UCF_ITEM_PROG_DETAIL_VCH11''
      ''UCF_ITEM_PROG_DETAIL_VCH12''
      ''UCF_ITEM_PROG_DETAIL_VCH13''
      ''UCF_ITEM_PROG_DETAIL_VCH14''
      ''UCF_ITEM_PROG_DETAIL_VCH15''
      ''UCF_ITEM_PROG_DETAIL_NUM1''
      ''UCF_ITEM_PROG_DETAIL_NUM2''
      ''UCF_ITEM_PROG_DETAIL_NUM3''
      ''UCF_ITEM_PROG_DETAIL_NUM4''
      ''UCF_ITEM_PROG_DETAIL_NUM5''
      ''UCF_ITEM_PROG_DETAIL_FLAG1''
      ''UCF_ITEM_PROG_DETAIL_FLAG2''
      ''UCF_ITEM_PROG_DETAIL_FLAG3''
      ''UCF_ITEM_PROG_DETAIL_FLAG4''
      ''UCF_ITEM_PROG_DETAIL_FLAG5''
      ''UCF_ITEM_PROG_DETAIL_DATE1''
      ''UCF_ITEM_PROG_DETAIL_DATE2''
      ''UCF_ITEM_PROG_DETAIL_DATE3''
      ''UCF_ITEM_PROG_DETAIL_DATE4''
      ''UCF_ITEM_PROG_DETAIL_DATE5''
      ''UCF_ITEM_PROG_DETAIL_VCH255_1''
      ''UCF_ITEM_PROG_DETAIL_VCH255_2''
      ''UCF_ITEM_PROG_DETAIL_VCH255_3''
      ''UCF_ITEM_PROG_DETAIL_VCH4000_1''
      ''UCF_ITEM_PROG_DETAIL_VCH4000_2''
      ''BUY_FLAG=''
      ''MAKE_FLAG=''
      ''AVG_PURCHASE_PRICE_PER_UNIT=''
      ''AVG_MATERIAL_COST_PER_UNIT=''
      ''AVG_LABOR_COST_PER_UNIT=''
      ''PRICE_COST_UNIT=''
      ''AVG_ORDER_LEAD_TIME_DAYS=''
      ''COMMODITY_JURISDICTION=''
      ''COMMODITY_CLASSIFICATION=''
      ''ASSOCIATE_CHANGE=''
      ''@TRANSACTIONTYPE'')
  end
  object TOVCController
  end
end';
v_iclob clob;
begin
v_iclob := p1||p2;
begin
  insert into sfcore_udv_lib(udv_id,udv_tag,updt_userid,time_stamp,udv_type,stype,udv_desc,state,load_ref,tool_version,object_rev,owner_group,udv_definition)
    values(v_udv_id,v_udv_tag,user,sysdate,v_udv_type,v_stype,v_udv_desc,v_state,v_load_ref,v_tool_version,v_object_rev,v_owner_group,
    replace(replace(v_iclob,chr(39)||chr(39)||chr(39),chr(39)||chr(39)),'POUND39_HOLDER',chr(35)||chr(51)||chr(57)));
  commit;
exception when dup_val_on_index then
  begin
    update sfcore_udv_lib
    set udv_definition=replace(replace(v_iclob,chr(39)||chr(39)||chr(39),chr(39)||chr(39)),'POUND39_HOLDER',chr(35)||chr(51)||chr(57)),updt_userid=user,time_stamp=sysdate,
      tool_version=v_tool_version,udv_tag=v_udv_tag,udv_desc = v_udv_desc,state=v_state,object_rev=v_object_rev,owner_group=v_owner_group,
      udv_type=v_udv_type,stype=v_stype
    where udv_id=v_udv_id;
    commit;
  exception when others then
  	 sffnd_show_execution_message('DML',v_udv_id, SQLCODE,SQLERRM,' update sfcore_udv_lib ');
  end;
when others then
  sffnd_show_execution_message('DML',v_udv_id, SQLCODE,SQLERRM,' insert into sfcore_udv_lib ');
end;
begin
 if v_folder_id is not null then
  insert into sfcore_udv_folder(udv_id,folder_id,updt_userid,time_stamp)
  values(v_udv_id,v_folder_id,user,sysdate);
  commit;
 end if;
exception when others then 
 sffnd_show_execution_message('DML',v_udv_id, SQLCODE,SQLERRM,' insert into sfcore_udv_folder ');
end;
end;
/

set define on

