
set define off
prompt ---------------------------------------;
prompt Executing ... PWUST_676C8855A27C97D1E05387971F0AD590.sql
prompt ---------------------------------------;
declare
v_folder_id sfcore_udv_folder.folder_id%type :='PWUST_550FF0D87F4141A0E05387971F0AD3EA';
v_udv_id sfcore_udv_lib.udv_id%type  :='PWUST_676C8855A27C97D1E05387971F0AD590';
v_udv_tag sfcore_udv_lib.udv_tag%type :='PWUST_OrderOperCrossDCExeUnitMtx';
v_udv_type sfcore_udv_lib.udv_type%type  :='INPMTX';
v_udv_desc sfcore_udv_lib.udv_desc%type  :='Defect 401; Order Oper Cross Order DC Execution Input Matrix; Adjusted so Comments are optional first time.';
v_state sfcore_udv_lib.state%type  :='';
v_load_ref sfcore_udv_lib.load_ref%type  :='';
v_tool_version sfcore_udv_lib.tool_version%type  :='2.4.2.0.20180714~2.4';
v_object_rev sfcore_udv_lib.object_rev%type  :='';
v_owner_group sfcore_udv_lib.owner_group%type  :='';
v_stype sfcore_udv_lib.stype%type  :='SFWID';
p1 clob :='object TCBScrollBox
  Left = 0
  Top = 0
  Width = 804
  Height = 100
  HelpContext = ''''
  AutoScroll = False
  DoubleBuffered = False
  ParentDoubleBuffered = False
  Caption = ''Collect Parameter Data''
  TransactionType = ttCached
  IMSqlTransactionName = ''OrderOperDatColIns''
  IMSqlSourceName = ''OrderOperDCExeInpMtx''
  IMScanAction = saIMAccept
  IMBatchCommit = True
  IMAllowHeaderChanges = False
  IMNoSelectionLoadsAll = etDefault
  IMFixedColCount = 6
  IMPopulateFromParams = False
  IMEndExecSqlId = ''MFI_WID_AUTO_START_NEXT_TASK''
  IMBatchTransactions = True
  UdvControlType = uctInputMatrix
  RequireLogonExpression = ''False''
  AutoCancelTimeout = -1
  MultimediaRequired = mmNo
  MMPopulateForInsert = False
  AlignContents = acTop
  SizeToEndOfLine = False
  AutoRefresh = arDefault
  MinWidth = 500
  MinHeight = 100
  MaxWidth = 900
  MaxHeight = 100
  UserAbort = etDefault
  ProgressMeter = etDefault
  AutoScrollbars = True
  DynamicFieldAttributes = False
  BottomMargin = -1
  object OrderOperDCExeInpMtx: TSfSqlSource
    SelectOnUserConnection = False
    SelectSqlId = ''OrderOperCrossDCExeUnitMtxSel''
    ParamsSQLSourceName = ''@ToolScope,@ScriptParams''
    PublishParams = True
    SelectedFields.Strings = (
      
        ''ORDER_NO~10~Order No~N~N~False~N~GROUP_JOB_NO = ''#39#39'' AND CROSS_ORD'' +
        ''ER_FLAG <> ''#39''Y''#39''~N~~~~~Default~N~~~''
      
        ''OPER_NO~3~Oper No~N~N~False~False~GROUP_JOB_NO = ''#39#39''~N~~~~~Defaul'' +
        ''t~N~~~''
      
        ''LOT_NO~5~Lot No~N~N~((ORDER_CONTROL_TYPE =''#39''NONE''#39'' OR ORDER_CONTRO'' +
        ''L_TYPE = ''#39''SERIAL1''#39'' OR ORDER_CONTROL_TYPE = ''#39''SERIAL''#39'') OR ((ORDER_'' +
        ''CONTROL_TYPE = ''#39''LOT1''#39'' OR ORDER_CONTROL_TYPE = ''#39''LOT''#39'') AND ORDER_Q'' +
        ''TY = ''#39''1''#39'' AND CROSS_ORDER_FLAG <> ''#39''Y''#39'')) AND GROUP_JOB_NO = ''#39#39''~N~('' +
        ''(ORDER_CONTROL_TYPE =''#39''NONE''#39'' OR ORDER_CONTROL_TYPE = ''#39''SERIAL1''#39'' OR'' +
        '' ORDER_CONTROL_TYPE = ''#39''SERIAL''#39'') OR ((ORDER_CONTROL_TYPE = ''#39''LOT1''#39 +
        '' OR ORDER_CONTROL_TYPE = ''#39''LOT''#39'') AND ORDER_QTY = ''#39''1''#39'' AND CROSS_OR'' +
        ''DER_FLAG <> ''#39''Y''#39'')) AND GROUP_JOB_NO = ''#39#39''~N~~~~~Default~N~~~''
      
        ''SERIAL_NO~5~Serial No~N~N~((ORDER_CONTROL_TYPE =''#39''NONE''#39'' OR ORDER_'' +
        ''CONTROL_TYPE = ''#39''LOT1''#39'' OR ORDER_CONTROL_TYPE = ''#39''LOT''#39'') OR ((ORDER_'' +
        ''CONTROL_TYPE = ''#39''SERIAL1''#39'' OR ORDER_CONTROL_TYPE = ''#39''SERIAL''#39'') AND O'' +
        ''RDER_QTY = ''#39''1''#39'' AND CROSS_ORDER_FLAG <> ''#39''Y''#39'')) AND GROUP_JOB_NO = '' +
        #39#39''~N~((ORDER_CONTROL_TYPE =''#39''NONE''#39'' OR ORDER_CONTROL_TYPE = ''#39''LOT1''#39 +
        '' OR ORDER_CONTROL_TYPE = ''#39''LOT''#39'') OR ((ORDER_CONTROL_TYPE = ''#39''SERIA'' +
        ''L1''#39'' OR ORDER_CONTROL_TYPE = ''#39''SERIAL''#39'') AND ORDER_QTY = ''#39''1''#39'' AND CR'' +
        ''OSS_ORDER_FLAG <> ''#39''Y''#39'')) AND GROUP_JOB_NO = ''#39#39''~N~~~~~Default~N~~~''
      ''DAT_COL_TYPE~7~Data Collection;Type~N~N~N~N~N~N~~~~~Default~N~~~''
      
        ''DAT_COL_TITLE~10~Data Collection;Title~N~N~N~N~N~N~~~~~Default~Y'' +
        ''~~~''
      ''DAT_COL_UOM~3~UOM~N~N~False~N~False~N~~~~~Default~N~~~''
      
        ''UCF_OPER_DC_FLAG1~1~ROM;Incl?~N~N~False~False~ORDER_TYPE<>''#39''REPAI'' +
        ''R''#39''~N~~~~~Default~N~~~''
      
        ''UCF_OPER_DC_VCH255_1~10~Engineering Cmts~N~N~False~False~ORDER_T'' +
        ''YPE<>''#39''REPAIR''#39''~N~~~~~Default~N~~~''
      
        ''AVAILABLE_QTY~5~Available;Qty~N~N~OPERATION_OVERLAP_FLAG=''#39''N''#39''~Fal'' +
        ''se~OPERATION_OVERLAP_FLAG=''#39''N''#39''~N~~~~~Default~N~~~''
      
        ''COMPLETE_QTY~6~Collected;Qty~N~N~OPERATION_OVERLAP_FLAG=''#39''N''#39''~Fals'' +
        ''e~OPERATION_OVERLAP_FLAG=''#39''N''#39''~N~~~~~Default~N~~~''
      ''LOWER_LIMIT~6~LSL~N~N~False~N~True~N~~~~~Default~N~~~''
      ''XBAR_CPL_VALUE~6~LCL~N~N~False~N~True~N~~~~~Default~N~~~''
      ''TARGET_VALUE~6~Target;Value~N~N~False~N~True~N~~~~~Default~N~~~''
      ''DCVALUE~5~Value~N~N~False~False~False~N~~~~~Default~N~~~''
      
        ''ACCEPT_REJECT~5~Accept/Reject~N~N~False~False~False~N~~~~~Defaul'' +
        ''t~N~~~''
      ''FILE1~12~File~N~N~False~False~False~N~~~~~Default~N~~~''
      ''SKIPPED~3~Skip~N~N~False~False~False~N~~~~~Default~N~~~''
      ''XBAR_CPU_VALUE~6~UCL~N~N~False~N~True~N~~~~~Default~N~~~''
      ''UPPER_LIMIT~6~USL~N~N~False~N~True~N~~~~~Default~N~~~''
      ''OUTSIDE~6~Outside;Limits?~N~N~False~N~True~N~~~~~Default~N~~~''
      ''DAT_COL_CERT~7~Required;Cert~N~N~False~N~True~N~~~~~Default~N~~~''
      ''COMMENTS~10~Comments~N~N~N~N~N~N~~~~~Default~N~~~''
      
        ''UCF_OPER_DC_FLAG2~1~Serviceable;Limit;Used~N~N~False~False~ORDER'' +
        ''_TYPE <> ''#39''REPAIR''#39''~N~~~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_NUM1~0~Ucf Srl Oper DC Num1~N~N~False~N~True~N~~'' +
        ''~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_NUM2~0~Ucf Srl Oper DC Num2~N~N~False~N~True~N~~'' +
        ''~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_NUM3~0~Ucf Srl Oper DC Num3~N~N~False~N~True~N~~'' +
        ''~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_NUM4~0~Ucf Srl Oper DC Num4~N~N~False~N~True~N~~'' +
        ''~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_NUM5~0~Ucf Srl Oper DC Num5~N~N~False~N~True~N~~'' +
        ''~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_FLAG1~0~Ucf Srl Oper DC Flag1~N~N~False~N~True~N'' +
        ''~~~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_FLAG2~0~Ucf Srl Oper DC Flag2~N~N~False~N~True~N'' +
        ''~~~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_FLAG3~0~Ucf Srl Oper DC Flag3~N~N~False~N~True~N'' +
        ''~~~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_FLAG4~0~Ucf Srl Oper DC Flag4~N~N~False~N~True~N'' +
        ''~~~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_FLAG5~0~Ucf Srl Oper DC Flag5~N~N~False~N~True~N'' +
        ''~~~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_DATE1~0~Ucf Srl Oper DC Date1~N~N~False~N~True~N'' +
        ''~~~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_DATE2~0~Ucf Srl Oper DC Date2~N~N~False~N~True~N'' +
        ''~~~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_DATE3~0~Ucf Srl Oper DC Date3~N~N~False~N~True~N'' +
        ''~~~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_DATE4~0~Ucf Srl Oper DC Date4~N~N~False~N~True~N'' +
        ''~~~~~Default~N~~~''
      
        ''UCF_SRL_OPER_DC_DATE5~0~Ucf Srl Oper DC Date5~N~N~False~N~True~N'' +
        ''~~~~~Default~N~~~''
      ''FORMAT~0~Format~N~N~True~False~True~N~~~~~Default~N~~~'')
    SelectedFieldsEditControl.Strings = (
      ''SKIPPED~CheckBox=1~0''
      ''DAT_COL_TITLE~Edit''
      ''LOWER_LIMIT~Edit''
      ''XBAR_CPL_VALUE~Edit''
      ''TARGET_VALUE~Edit''
      ''UCF_SRL_OPER_DC_NUM2~Edit''
      ''UCF_SRL_OPER_DC_NUM3~Edit''
      ''UCF_SRL_OPER_DC_NUM4~Edit''
      ''UCF_SRL_OPER_DC_NUM5~Edit''
      ''UCF_SRL_OPER_DC_FLAG1~Edit''
      ''UCF_SRL_OPER_DC_FLAG2~Edit''
      ''UCF_SRL_OPER_DC_FLAG3~Edit''
      ''UCF_SRL_OPER_DC_FLAG4~Edit''
      ''UCF_SRL_OPER_DC_FLAG5~Edit''
      ''UCF_SRL_OPER_DC_DATE1~Edit''
      ''UCF_SRL_OPER_DC_DATE2~Edit''
      ''UCF_SRL_OPER_DC_DATE3~Edit''
      ''DCVALUE~Edit''
      ''OPER_NO~Edit''
      ''LOT_NO~Edit''
      ''SERIAL_NO~Edit''
      ''UCF_OPER_DC_FLAG2~CheckBox=1~0''
      ''UCF_OPER_DC_FLAG1~CheckBox=1~0''
      ''COMPLETE_QTY~Edit''
      ''AVAILABLE_QTY~Edit''
      ''ORDER_NO~Edit''
      ''COMMENTS~Edit'')
    TestParamValues.Strings = (
      ''oper_key=409362''
      ''step_key=-1''
      ''order_no=WO0000053''
      ''lot_no=N/A''
      ''serial_no=N/A''
      ''order_control_type=NONE''
      ''dat_col_id=PWUST_5BEB8D84BCD28BF411D570CBF662585D''
      ''order_id=6A87D7CA2E327D39E203750EAD216931''
      ''called_from=GRID''
      ''GROUP_JOB_NO='')
    DataDefinitions.Strings = (
      ''ORDER_NO''
      ''OPER_NO''
      ''LOT_NO''
      ''SERIAL_NO''
      ''DAT_COL_TYPE''
      ''DAT_COL_TITLE''
      ''DAT_COL_UOM''
      ''UCF_OPER_DC_FLAG1''
      ''UCF_OPER_DC_VCH255_1''
      ''AVAILABLE_QTY''
      ''COMPLETE_QTY''
      ''LOWER_LIMIT''
      ''XBAR_CPL_VALUE''
      ''TARGET_VALUE''
      ''DCVALUE''
      ''ACCEPT_REJECT''
      ''FILE1''
      ''SKIPPED''
      ''XBAR_CPU_VALUE''
      ''UPPER_LIMIT''
      ''OUTSIDE''
      ''DAT_COL_CERT''
      ''COMMENTS''
      ''UCF_OPER_DC_FLAG2''
      ''UCF_SRL_OPER_DC_NUM1''
      ''UCF_SRL_OPER_DC_NUM2''
      ''UCF_SRL_OPER_DC_NUM3''
      ''UCF_SRL_OPER_DC_NUM4''
      ''UCF_SRL_OPER_DC_NUM5''
      ''UCF_SRL_OPER_DC_FLAG1''
      ''UCF_SRL_OPER_DC_FLAG2''
      ''UCF_SRL_OPER_DC_FLAG3''
      ''UCF_SRL_OPER_DC_FLAG4''
      ''UCF_SRL_OPER_DC_FLAG5''
      ''UCF_SRL_OPER_DC_DATE1''
      ''UCF_SRL_OPER_DC_DATE2''
      ''UCF_SRL_OPER_DC_DATE3''
      ''UCF_SRL_OPER_DC_DATE4''
      ''UCF_SRL_OPER_DC_DATE5''
      ''FORMAT'')
    ConsolidatedQuery = False
  end
  object OrderOperDatColIns: TSfSqlTransaction
    InputFieldsSSL.Strings = (
      ''ORDER_ID''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''OPER_KEY''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''STEP_KEY''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''DAT_COL_ID''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''SERIAL_NO''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''COMMENTS''
      '' Update=SHOW_CDC=''#39''Y''#39
      '' Insert=SHOW_CDC=''#39''Y''#39
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' MaxLength=255''
      '' PersistManualValues=Y''
      ''DAT_COL_CERT''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' MaxLength=30''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_NUM1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_NUM2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_NUM3''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_NUM4''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_NUM5''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_FLAG1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=Y''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_FLAG2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=Y''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_FLAG3''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=Y''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_FLAG4''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=Y''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_FLAG5''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' MaxLength=1''
      '' CharCase=Y''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_DATE1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_DATE2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_DATE3''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_DATE4''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''UCF_SRL_OPER_DC_DATE5''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''LOT_NO''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=Y''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''ORDER_NO''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Hidden=False''
      '' Required=False''
      '' PersistManualValues=Y''
      ''DCVALUE''
      
        '' Update=FORMAT = ''#39''File''#39'' OR FORMAT = ''#39''Accept/Reject''#39'' OR (DCVALUE '' +
        ''<> ''#39#39'' AND OPERATION_OVERLAP_FLAG = ''#39''Y''#39'') OR SHOW_CDC=''#39''Y''#39
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' Required=False''
      '' PersistManualValues=N''
      '' Hidden=False''
      '' MaxLength=4000''
      ''UCF_SRL_OPER_DC_VCH1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH3''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH4''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH5''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH6''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH7''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH8''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH9''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH10''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH11''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH12''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH13''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH14''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH15''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH255_1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH255_2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH255_3''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH4000_1''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_SRL_OPER_DC_VCH4000_2''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''FILE1''
      
        '' Update=FORMAT <> ''#39''File''#39'' OR (FILE1 <> ''#39#39'' AND OPERATION_OVERLAP_F'' +
        ''LAG = ''#39''Y''#39'')''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''FILE1_DATA''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''OLD_USERID''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''SKIPPED''
      '' AuxField=Y''
      
        '' Update=(DCVALUE <> ''#39#39'' OR ACCEPT_REJECT <> ''#39#39'' OR FILE1 <> ''#39#39'') AN'' +
        ''D OPERATION_OVERLAP_FLAG = ''#39''Y''#39
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      
        '' Hidden=OPTIONAL_FLAG = ''#39''N''#39'' OR DCVALUE <> ''#39#39'' OR ACCEPT_REJECT <>'' +
        '' ''#39#39'' OR FILE1 <> ''#39#39
      '' Required=False''
      ''SERIAL_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''ORDER_QTY''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''PROGRAM''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''ORDER_CONTROL_TYPE''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''CROSS_ORDER_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''ORIENTATION_FLAG''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''OPER_STATUS''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''AVAILABLE_QTY''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''COMPLETE_QTY''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''GROUP_JOB_NO''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''GROUP_JOB_INFO''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''ACCEPT_REJECT''
      '' Update=FORMAT <> ''#39''Accept/Reject''#39
      '' Insert=False''
      '' PopulateForInsert=N''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''@USERID''
      ''UCF_OPER_DC_FLAG1''
      '' AuxField=Y''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      '' DefaultValue=N''
      ''UCF_OPER_DC_VCH255_1''
      '' AuxField=Y''
      '' Update=True''
      '' Insert=True''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False''
      ''UCF_OPER_DC_FLAG2''
      '' AuxField=Y''
      '' Update=False''
      '' Insert=False''
      '' PopulateForInsert=Y''
      '' CharCase=N''
      '' PersistManualValues=Y''
      '' Hidden=False''
      '' Required=False'')
    InputFieldsEditControlSSL.Strings = (
      ''UCF_SRL_OPER_DC_VCH4000_2''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH255_3''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH255_2''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH255_1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH15''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH14''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH13''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH12''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH11''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH10''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH9''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH8''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH7''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH6''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH5''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH4''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH3''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH2''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''SERIAL_NO''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_NUM4''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_NUM5''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_FLAG4''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_FLAG5''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_DATE1''
      '' CtrlType=Edit''
      ''  DataType=Date''
      ''  Format=Windows Default''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_DATE2''
      '' CtrlType=Edit''
      ''  DataType=Date''
      ''  Format=Windows Default''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_DATE3''
      '' CtrlType=Edit''
      ''  DataType=Date''
      ''  Format=Windows Default''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_DATE5''
      '' CtrlType=Edit''
      ''  DataType=Date''
      ''  Format=Windows Default''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''LOT_NO''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''ORDER_NO''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''GROUP_JOB_INFO''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''COMPLETE_QTY''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''AVAILABLE_QTY''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''OPER_STATUS''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''ORIENTATION_FLAG''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''CROSS_ORDER_FLAG''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''ORDER_CONTROL_TYPE''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''PROGRAM''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''ORDER_QTY''
      '' CtrlType=Edit''
      ''  DataType=Alphan';
p2 clob :='umeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''OLD_USERID''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''FILE1_DATA''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''FILE1''
      '' CtrlType=Edit''
      ''  DataType=Filename With Data''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_DATE4''
      '' CtrlType=Edit''
      ''  DataType=Date''
      ''  Format=Windows Default''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''DCVALUE''
      '' CtrlType=Lookup''
      ''  SqlId=MFI_WID_OrderDCSelectableValueLookup''
      ''  Validate=N''
      ''  DefaultToSingle=N''
      ''  ForceLookup=N''
      ''  IMLookupFilter=N''
      ''  ShortLookupDelim=|''
      ''  VisibleFields''
      ''  Style=Short''
      ''   Static=N''
      ''SKIPPED''
      '' CtrlType=List''
      ''  Values=N~Y''
      ''UCF_SRL_OPER_DC_NUM3''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''DAT_COL_CERT''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''SERIAL_FLAG''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH4000_1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''GROUP_JOB_NO''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=Now''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_NUM2''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''STEP_KEY''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''COMMENTS''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''DAT_COL_ID''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''OPER_KEY''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_VCH1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_NUM1''
      '' CtrlType=Edit''
      ''  DataType=Numeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_FLAG2''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_SRL_OPER_DC_FLAG3''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''ACCEPT_REJECT''
      '' CtrlType=List''
      ''  Values=Accept~Reject''
      ''UCF_SRL_OPER_DC_FLAG1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_OPER_DC_FLAG2''
      '' CtrlType=List''
      ''  Values=N~Y''
      ''UCF_OPER_DC_VCH255_1''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=AsIs''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''ORDER_ID''
      '' CtrlType=Edit''
      ''  DataType=Alphanumeric''
      ''  Decimal=0''
      ''  Currency=N''
      ''  AllowManaging=N''
      ''  SelectFolder=N''
      ''UCF_OPER_DC_FLAG1''
      '' CtrlType=Edit''
      ''  Decimal=0''
      ''  Currency=N''
      ''  TimeAlgorithm=AsIs''
      ''  AllowManaging=N''
      ''  SelectFolder=N'')
    CancelSqlId = ''MFI_WID_USER_OPER_SESSION_DELETE''
    UpdateSqlId = ''PWUST_WID_DatColExePre''
    ParamsSQLSourceName = ''@ToolScope,@ScriptParams''
    RefreshParams = False
    MultiRecordTransaction = mruTrue
    RefreshedSQLSourceName = ''OrderOperDatColSerSel''
    DataDefinitions.Strings = (
      ''ORDER_ID=''
      ''OPER_KEY=''
      ''STEP_KEY=''
      ''DAT_COL_ID=''
      ''SERIAL_NO=''
      ''COMMENTS=''
      ''DAT_COL_CERT=''
      ''UCF_SRL_OPER_DC_NUM1=''
      ''UCF_SRL_OPER_DC_NUM2=''
      ''UCF_SRL_OPER_DC_NUM3=''
      ''UCF_SRL_OPER_DC_NUM4=''
      ''UCF_SRL_OPER_DC_NUM5=''
      ''UCF_SRL_OPER_DC_FLAG1=''
      ''UCF_SRL_OPER_DC_FLAG2=''
      ''UCF_SRL_OPER_DC_FLAG3=''
      ''UCF_SRL_OPER_DC_FLAG4=''
      ''UCF_SRL_OPER_DC_FLAG5=''
      ''UCF_SRL_OPER_DC_DATE1=''
      ''UCF_SRL_OPER_DC_DATE2=''
      ''UCF_SRL_OPER_DC_DATE3=''
      ''UCF_SRL_OPER_DC_DATE4=''
      ''UCF_SRL_OPER_DC_DATE5=''
      ''LOT_NO=''
      ''ORDER_NO=''
      ''DCVALUE=''
      ''UCF_SRL_OPER_DC_VCH1=''
      ''UCF_SRL_OPER_DC_VCH2=''
      ''UCF_SRL_OPER_DC_VCH3=''
      ''UCF_SRL_OPER_DC_VCH4=''
      ''UCF_SRL_OPER_DC_VCH5=''
      ''UCF_SRL_OPER_DC_VCH6=''
      ''UCF_SRL_OPER_DC_VCH7=''
      ''UCF_SRL_OPER_DC_VCH8=''
      ''UCF_SRL_OPER_DC_VCH9=''
      ''UCF_SRL_OPER_DC_VCH10=''
      ''UCF_SRL_OPER_DC_VCH11=''
      ''UCF_SRL_OPER_DC_VCH12=''
      ''UCF_SRL_OPER_DC_VCH13=''
      ''UCF_SRL_OPER_DC_VCH14=''
      ''UCF_SRL_OPER_DC_VCH15=''
      ''UCF_SRL_OPER_DC_VCH255_1=''
      ''UCF_SRL_OPER_DC_VCH255_2=''
      ''UCF_SRL_OPER_DC_VCH255_3=''
      ''UCF_SRL_OPER_DC_VCH4000_1=''
      ''UCF_SRL_OPER_DC_VCH4000_2=''
      ''FILE1=''
      ''FILE1_DATA=''
      ''OLD_USERID=''
      ''SKIPPED=''
      ''SERIAL_FLAG=''
      ''ORDER_QTY=''
      ''PROGRAM=''
      ''ORDER_CONTROL_TYPE=''
      ''CROSS_ORDER_FLAG=''
      ''ORIENTATION_FLAG=''
      ''OPER_STATUS=''
      ''AVAILABLE_QTY=''
      ''COMPLETE_QTY=''
      ''GROUP_JOB_NO=''
      ''GROUP_JOB_INFO=''
      ''ACCEPT_REJECT=''
      ''@USERID'')
  end
end';
v_iclob clob;
begin
v_iclob := p1||p2;
begin
  insert into sfcore_udv_lib(udv_id,udv_tag,updt_userid,time_stamp,udv_type,stype,udv_desc,state,load_ref,tool_version,object_rev,owner_group,udv_definition)
    values(v_udv_id,v_udv_tag,user,sysdate,v_udv_type,v_stype,v_udv_desc,v_state,v_load_ref,v_tool_version,v_object_rev,v_owner_group,
    replace(replace(v_iclob,chr(39)||chr(39)||chr(39),chr(39)||chr(39)),'POUND39_HOLDER',chr(35)||chr(51)||chr(57)));
  commit;
exception when dup_val_on_index then
  begin
    update sfcore_udv_lib
    set udv_definition=replace(replace(v_iclob,chr(39)||chr(39)||chr(39),chr(39)||chr(39)),'POUND39_HOLDER',chr(35)||chr(51)||chr(57)),updt_userid=user,time_stamp=sysdate,
      tool_version=v_tool_version,udv_tag=v_udv_tag,udv_desc = v_udv_desc,state=v_state,object_rev=v_object_rev,owner_group=v_owner_group,
      udv_type=v_udv_type,stype=v_stype
    where udv_id=v_udv_id;
    commit;
  exception when others then
  	 sffnd_show_execution_message('DML',v_udv_id, SQLCODE,SQLERRM,' update sfcore_udv_lib ');
  end;
when others then
  sffnd_show_execution_message('DML',v_udv_id, SQLCODE,SQLERRM,' insert into sfcore_udv_lib ');
end;
begin
 if v_folder_id is not null then
  insert into sfcore_udv_folder(udv_id,folder_id,updt_userid,time_stamp)
  values(v_udv_id,v_folder_id,user,sysdate);
  commit;
 end if;
exception when others then 
 sffnd_show_execution_message('DML',v_udv_id, SQLCODE,SQLERRM,' insert into sfcore_udv_folder ');
end;
end;
/

set define on

