DECLARE
V_DUMMY VARCHAR2(10);
BEGIN
SELECT 'DUMMY' INTO V_DUMMY FROM USER_TABLES WHERE TABLE_NAME = 'PWUST_ENGINE_TYPE_MODEL_DEF';
EXCEPTION
WHEN NO_DATA_FOUND THEN
  
EXECUTE IMMEDIATE ('CREATE TABLE PWUST_ENGINE_TYPE_MODEL_DEF(
  ENGINE_TYPE          VARCHAR2(30) NOT NULL,
  MODEL                VARCHAR2(20) NOT NULL,
  UPDT_USERID          VARCHAR2(30) DEFAULT USER NOT NULL,
  TIME_STAMP           DATE DEFAULT SYSDATE NOT NULL,
  ACTION               VARCHAR2(20) DEFAULT ''INSERTED'' NOT NULL,
  OBSOLETE_RECORD_FLAG CHAR(1) DEFAULT ''N'',
  PROGRAM_MODEL_DESC   VARCHAR2(50)
) TABLESPACE SFUPGRADE');

EXECUTE IMMEDIATE ('ALTER TABLE PWUST_ENGINE_TYPE_MODEL_DEF   ADD CONSTRAINT PWUST_ENGINE_TYPE_MODEL_DEF_PK PRIMARY KEY (ENGINE_TYPE, MODEL)  USING INDEX    TABLESPACE SFUPGRADE');
EXECUTE IMMEDIATE ('ALTER TABLE PWUST_ENGINE_TYPE_MODEL_DEF ADD CONSTRAINT PWUST_ENGINE_TYPE_MODELDEF_FK1 FOREIGN KEY (ENGINE_TYPE) REFERENCES SFFND_PROGRAM_DEF (PROGRAM)');
EXECUTE IMMEDIATE ('ALTER TABLE PWUST_ENGINE_TYPE_MODEL_DEF  ADD CONSTRAINT PWUST_ENGINE_TYPE_MODELDEF_FK2 FOREIGN KEY (MODEL) REFERENCES SFFND_MODEL_DEF (MODEL)');
EXECUTE IMMEDIATE ('GRANT SELECT ON PWUST_ENGINE_TYPE_MODEL_DEF TO PRATT_READ_ONLY');
EXECUTE IMMEDIATE ('GRANT SELECT, INSERT, UPDATE, DELETE ON PWUST_ENGINE_TYPE_MODEL_DEF TO SF$CONNECTION_POOL');
end;
/