BEGIN
  UPDATE SFPL_STEP_BUYOFF
     SET UCF_STEP_BUYOFF_VCH1  = NULL,
         UCF_STEP_BUYOFF_VCH2  = NULL,
         UCF_STEP_BUYOFF_VCH3  = NULL,
         UCF_STEP_BUYOFF_DATE1 = NULL,
         UCF_STEP_BUYOFF_NUM1  = NULL
   WHERE UCF_STEP_BUYOFF_VCH1 IS NOT NULL
      OR UCF_STEP_BUYOFF_VCH2 IS NOT NULL
      OR UCF_STEP_BUYOFF_VCH3 IS NOT NULL
      OR UCF_STEP_BUYOFF_DATE1 IS NOT NULL
      OR UCF_STEP_BUYOFF_NUM1 IS NOT NULL;
  
   COMMIT;
END;
