BEGIN
  DECLARE
    DOES_NOT_EXIST EXCEPTION;
    PRAGMA EXCEPTION_INIT(DOES_NOT_EXIST, -4043);
  BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE PWUST_CLEAN_EXTRACT_TABLES';
  EXCEPTION
    WHEN DOES_NOT_EXIST THEN NULL;
  END;
END;
/
