ALTER TABLE VIS_GRAPHIC ADD PLAN_ID VARCHAR2(40);
ALTER TABLE VIS_GRAPHIC ADD PART_NO VARCHAR2(50);
ALTER TABLE VIS_GRAPHIC ADD OPER_NO VARCHAR2(10);
ALTER TABLE VIS_GRAPHIC ADD STEP_NO VARCHAR2(10);
