--Defect 412
alter table PWUST_OVERHAUL_ORDER_ERRORS modify WORK_SCOPE VARCHAR2(2000);
alter table PWUST_OVERHAUL_ORDER_ERRORS modify SUPERIOR_NETWORK_ACT VARCHAR2(2000);
alter table PWUST_OVERHAUL_ORDER_ERRORS modify SUB_NETWORK_ACT VARCHAR2(2000);
alter table PWUST_OVERHAUL_ORDER_ERRORS modify CUSTOMER VARCHAR2(2000);