--Defect 412
alter table PWUST_PLANNED_ORDERS modify WORK_SCOPE VARCHAR2(2000);
alter table PWUST_PLANNED_ORDERS modify SUPERIORNET VARCHAR2(2000);
alter table PWUST_PLANNED_ORDERS modify SUBNET VARCHAR2(2000);
alter table PWUST_PLANNED_ORDERS modify CUSTOMER VARCHAR2(2000);