--------------------------------------------------------
--  DDL for Table PWPERF_ERRLOG
--------------------------------------------------------

  CREATE TABLE "SFMFG"."PWPERF_ERRLOG" 
   (	"ERRCODE" NUMBER(*,0), 
	"ERRMSG" VARCHAR2(200 BYTE), 
	"ERRVAL" VARCHAR2(200 BYTE), 
	"CREATED_ON" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"MACHINE" VARCHAR2(100 BYTE), 
	"PROGRAM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SFUPGRADE" ;

--------------------------------------------------------
--  DDL for Table PWPERF_EVENT_TREND
--------------------------------------------------------

  CREATE TABLE "SFMFG"."PWPERF_EVENT_TREND" 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"EVENT" VARCHAR2(64 BYTE), 
	"WAITS" NUMBER, 
	"TIME" NUMBER, 
	"PCTWTT" NUMBER(6,2), 
	"BEGIN_SNAP_TIME" DATE, 
	"DB_NAME" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SFUPGRADE" ;
--------------------------------------------------------
--  DDL for Index PWPERF_EVENT_TREND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SFMFG"."PWPERF_EVENT_TREND_PK" ON "SFMFG"."PWPERF_EVENT_TREND" ("SNAP_ID", "DBID", "INSTANCE_NUMBER", "EVENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SFUPGRADE" ;
--------------------------------------------------------
--  Constraints for Table PWPERF_EVENT_TREND
--------------------------------------------------------

  ALTER TABLE "SFMFG"."PWPERF_EVENT_TREND" ADD CONSTRAINT "PWPERF_EVENT_TREND_PK" PRIMARY KEY ("SNAP_ID", "DBID", "INSTANCE_NUMBER", "EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SFUPGRADE"  ENABLE;
  ALTER TABLE "SFMFG"."PWPERF_EVENT_TREND" MODIFY ("BEGIN_SNAP_TIME" NOT NULL ENABLE);
  ALTER TABLE "SFMFG"."PWPERF_EVENT_TREND" MODIFY ("EVENT" NOT NULL ENABLE);
  ALTER TABLE "SFMFG"."PWPERF_EVENT_TREND" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SFMFG"."PWPERF_EVENT_TREND" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SFMFG"."PWPERF_EVENT_TREND" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  DDL for Table PWPERF_LIOS_TREND
--------------------------------------------------------

  CREATE TABLE "SFMFG"."PWPERF_LIOS_TREND" 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"HASH_VALUE" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"MODULE" VARCHAR2(64 BYTE), 
	"BUFFER_GETS" NUMBER, 
	"EXECUTIONS" NUMBER, 
	"BGETS_PER_EXEC" NUMBER(18,2), 
	"DISK_READS" NUMBER, 
	"CPU_TIME" NUMBER(18,2), 
	"ELAPSED_TIME" NUMBER(18,2), 
	"SQL_TEXT" VARCHAR2(4000 BYTE), 
	"BEGIN_SNAP_TIME" DATE, 
	"DB_NAME" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SFUPGRADE" ;
--------------------------------------------------------
--  DDL for Index PWPERF_LIOS_TREND_IDX1
--------------------------------------------------------

  CREATE INDEX "SFMFG"."PWPERF_LIOS_TREND_IDX1" ON "SFMFG"."PWPERF_LIOS_TREND" ("SNAP_ID", "DBID", "INSTANCE_NUMBER", "BEGIN_SNAP_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SFUPGRADE" ;
--------------------------------------------------------
--  DDL for Index PWPERF_LIOS_TREND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SFMFG"."PWPERF_LIOS_TREND_PK" ON "SFMFG"."PWPERF_LIOS_TREND" ("SNAP_ID", "DBID", "INSTANCE_NUMBER", "SQL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SFUPGRADE" ;
--------------------------------------------------------
--  Constraints for Table PWPERF_LIOS_TREND
--------------------------------------------------------

  ALTER TABLE "SFMFG"."PWPERF_LIOS_TREND" ADD CONSTRAINT "PWPERF_LIOS_TREND_PK" PRIMARY KEY ("SNAP_ID", "DBID", "INSTANCE_NUMBER", "SQL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SFUPGRADE"  ENABLE;
  ALTER TABLE "SFMFG"."PWPERF_LIOS_TREND" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SFMFG"."PWPERF_LIOS_TREND" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SFMFG"."PWPERF_LIOS_TREND" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  DDL for Table PWPERF_SPACE_TREND
--------------------------------------------------------

  CREATE TABLE "SFMFG"."PWPERF_SPACE_TREND" 
   (	"SNAP_DATE" DATE, 
	"DBID" NUMBER, 
	"DB_NAME" VARCHAR2(9 BYTE), 
	"HOST_NAME" VARCHAR2(64 BYTE), 
	"USED_BLOCKS" NUMBER, 
	"USED_GB" NUMBER(12,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SFUPGRADE" ;
--------------------------------------------------------
--  DDL for Index PWPERF_SPACE_TREND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SFMFG"."PWPERF_SPACE_TREND_PK" ON "SFMFG"."PWPERF_SPACE_TREND" ("SNAP_DATE", "DBID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SFUPGRADE" ;
--------------------------------------------------------
--  Constraints for Table PWPERF_SPACE_TREND
--------------------------------------------------------

  ALTER TABLE "SFMFG"."PWPERF_SPACE_TREND" ADD CONSTRAINT "PWPERF_SPACE_TREND_PK" PRIMARY KEY ("SNAP_DATE", "DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SFUPGRADE"  ENABLE;


--------------------------------------------------------
--  DDL for Table PWPERF_STATS_TREND
--------------------------------------------------------

  CREATE TABLE "SFMFG"."PWPERF_STATS_TREND" 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"DB_NAME" VARCHAR2(9 BYTE), 
	"BEGIN_SNAP_TIME" DATE, 
	"END_SNAP_TIME" DATE, 
	"SNAP_DURATION" NUMBER, 
	"HARD_PARSES_SEC" NUMBER, 
	"EXECS_SEC" NUMBER, 
	"TRANS_SEC" NUMBER, 
	"LIBRARY_HIT_RATIO" NUMBER(9,2), 
	"SOFT_PARSE_RATIO" NUMBER(9,2), 
	"EXEC_WO_PARSE_RATIO" NUMBER(9,2), 
	"OS_LOAD" NUMBER(4,1), 
	"DB_CPU_APS" NUMBER(4,1), 
	"HOST_CPU" NUMBER(4,1), 
	"NETWORK_VOL" NUMBER(9,0), 
	"PHY_READS_RQS" NUMBER, 
	"PHY_READS_BPS" NUMBER, 
	"PHY_WRITES_RQS" NUMBER, 
	"PHY_WRITES_BPS" NUMBER, 
	"REDO_IOPS" NUMBER, 
	"REDO_BPS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SFUPGRADE" ;
--------------------------------------------------------
--  DDL for Index PWPERF_STATS_TREND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SFMFG"."PWPERF_STATS_TREND_PK" ON "SFMFG"."PWPERF_STATS_TREND" ("SNAP_ID", "DBID", "INSTANCE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SFUPGRADE" ;
--------------------------------------------------------
--  Constraints for Table PWPERF_STATS_TREND
--------------------------------------------------------

  ALTER TABLE "SFMFG"."PWPERF_STATS_TREND" ADD CONSTRAINT "PWPERF_STATS_TREND_PK" PRIMARY KEY ("SNAP_ID", "DBID", "INSTANCE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SFUPGRADE"  ENABLE;
  ALTER TABLE "SFMFG"."PWPERF_STATS_TREND" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SFMFG"."PWPERF_STATS_TREND" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SFMFG"."PWPERF_STATS_TREND" MODIFY ("SNAP_ID" NOT NULL ENABLE);





