DECLARE
V_DUMMY VARCHAR2(10);
BEGIN
SELECT 1 INTO V_DUMMY FROM DBA_TAB_COLUMNS T WHERE T.TABLE_NAME ='PW_S_T314_DISPOSITION_LOG' AND T.COLUMN_NAME = 'MESSAGE_ID' AND T.DATA_LENGTH = 40;
EXECUTE IMMEDIATE('ALTER TABLE PW_S_T314_DISPOSITION_LOG  MODIFY  (MESSAGE_ID  VARCHAR2(51))');
EXCEPTION
WHEN NO_DATA_FOUND THEN
NULL;
END;
/
--
DECLARE
V_DUMMY VARCHAR2(10);
BEGIN
SELECT 1 INTO V_DUMMY FROM DBA_TAB_COLUMNS T WHERE T.TABLE_NAME ='PW_S_T314_DISPOSITION_RPLY' AND T.COLUMN_NAME = 'MESSAGE_ID' AND T.DATA_LENGTH = 40;
EXECUTE IMMEDIATE('ALTER TABLE PW_S_T314_DISPOSITION_RPLY  MODIFY  (MESSAGE_ID  VARCHAR2(51))');
EXCEPTION
WHEN NO_DATA_FOUND THEN
NULL;
END;
/
--
DECLARE
V_DUMMY VARCHAR2(10);
BEGIN
SELECT 1 INTO V_DUMMY FROM DBA_TAB_COLUMNS T WHERE T.TABLE_NAME ='PW_S_T314_DISPOSITION_RPLY' AND T.COLUMN_NAME = 'ORIGINAL_MESSAGE_ID' AND T.DATA_LENGTH = 40;
EXECUTE IMMEDIATE('ALTER TABLE PW_S_T314_DISPOSITION_RPLY  MODIFY  (ORIGINAL_MESSAGE_ID  VARCHAR2(51))');
EXCEPTION
WHEN NO_DATA_FOUND THEN
NULL;
END;
/