DECLARE

  CURSOR CSR IS
    SELECT C.TABLE_NAME, C.CONSTRAINT_NAME
      FROM DBA_CONSTRAINTS C
     WHERE C.TABLE_NAME LIKE 'VIS%'
       AND C.CONSTRAINT_TYPE = 'R';

BEGIN

  FOR REC IN CSR
  LOOP
  
    EXECUTE IMMEDIATE 'ALTER TABLE ' || REC.TABLE_NAME || ' DROP CONSTRAINT ' ||
                      REC.CONSTRAINT_NAME;
  END LOOP;

EXCEPTION
  WHEN OTHERS THEN
    SFCORE_RAISE_ERROR('MFI_20','Some VIS table FK failed to drop');
END;
/
