ALTER TABLE PWMROI_ORDER_SUBJECT_AUTHORITY 
ADD SEQNO NUMBER NULL;
COMMIT;

CREATE SEQUENCE PWMROI_ORDER_SUBJ_AUTH_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
COMMIT;

grant select on sfmfg.PWMROI_ORDER_SUBJ_AUTH_SEQ to SF$CONNECTION_POOL;
commit;

UPDATE PWMROI_ORDER_SUBJECT_AUTHORITY
   SET SEQNO = PWMROI_ORDER_SUBJ_AUTH_SEQ.nextval;
COMMIT;

ALTER TABLE  PWMROI_ORDER_SUBJECT_AUTHORITY MODIFY SEQNO NOT NULL;
COMMIT;

ALTER TABLE PWMROI_ORDER_SUBJECT_AUTHORITY DROP CONSTRAINT PWMROI_ORDER_SUBJ_AUTH_PK;

ALTER TABLE PWMROI_ORDER_SUBJECT_AUTHORITY ADD CONSTRAINT PWMROI_ORDER_SUBJ_AUTH_PK PRIMARY KEY (ORDER_ID, SUBJECT_NO, SUBJECT_REV, AUTHORITY_TYPE, AUTHORITY_DETAIL, MANUAL_NO, MANUAL_REV,SEQNO);
COMMIT;