drop table PWUST_TEMP_ORDER_CREATE_DATA;

create global temporary table PWUST_TEMP_ORDER_CREATE_DATA
(
  PRIMERY_KEY      VARCHAR2(40) not null,
  SALES_ORDER      VARCHAR2(20),
  ENGINE_TYPE      VARCHAR2(9),
  ENGINE_MODEL     VARCHAR2(18),
  SAPWORKLOC       VARCHAR2(4),
  WORK_SCOPE       VARCHAR2(2000),
  ITEM_NO_SEL      VARCHAR2(50),
  SUPERIORNET      VARCHAR2(2000),
  SUBNET           VARCHAR2(2000),
  CUSTOMER         VARCHAR2(2000),
  PLANNEDORDERFLAG VARCHAR2(40),
  PLAN_ID          VARCHAR2(40),
  PLAN_VERSION     NUMBER,
  PLAN_REVISION    NUMBER,
  PLAN_ALTERATIONS NUMBER,
  PLAN_UPDT_NO     NUMBER,
  PART_NO          VARCHAR2(50),
  PART_CHG         VARCHAR2(20),
  UPDT_USERID      VARCHAR2(50) default USER not null,
  TIME_STAMP       DATE default SYSDATE not null
)on commit delete rows;

grant select on PWUST_TEMP_ORDER_CREATE_DATA to PRATT_READ_ONLY;
grant select, insert, update, delete on PWUST_TEMP_ORDER_CREATE_DATA to SF$CONNECTION_POOL;
