-- For SMRO_PLG_313
CREATE OR REPLACE VIEW SFMFG.PWUST_SFPL_DAT_COL_V AS
SELECT A.PLAN_ID,A.PLAN_VERSION,A.PLAN_REVISION,A.PLAN_ALTERATIONS,
A.OPER_NO,A.OPER_KEY,
A.STEP_NO,
A.STEP_KEY,A.STEP_UPDT_NO,B.DAT_COL_ID,E.DAT_COL_TYPE,B.DAT_COL_CERT,B.UPDT_USERID,
B.TIME_STAMP,B.LAST_ACTION,B.DAT_COL_UOM,B.DAT_COL_TITLE,b.ref_id,b.display_line_no,b.orientation_flag,
 b.cross_order_flag,optional_flag, variable_name,visibility,num_decimal_digits,calc_dc_flag, 
 b.block_id,SLIDE_ID,SLIDE_EMBEDDED_REF_ID,B.AUDIT_FLAG, b.STD_DATCOL_ID, B.RESULT_ID, B.TEMPLATE_FILE_ID,
 B.UCF_STEP_DC_FLAG1,
 B.UCF_STEP_DC_FLAG2,
 B.UCF_STEP_DC_VCH255_1
FROM SFMFG.SFPL_STEP_REV A,SFMFG.SFPL_STEP_DAT_COL B, SFMFG.SFFND_STD_DATCOL_TYPE_DEF E
 WHERE a.plan_id = b.plan_id
   AND a.oper_key = b.oper_key
   AND a.step_key = b.step_key
   AND a.step_updt_no = b.step_updt_no
   AND b.STD_DATCOL_ID = E.STD_DATCOL_ID;

GRANT SELECT ON SFMFG.PWUST_SFPL_DAT_COL_V TO PRATT_READ_ONLY;
GRANT DELETE, INSERT, SELECT, UPDATE ON SFMFG.PWUST_SFPL_DAT_COL_V TO SF$CONNECTION_POOL;
