CREATE OR REPLACE VIEW PWUST_NETWORK_DEF_MAP_V AS
SELECT T.STD_NETWORK_NO AS NETWORK_NO,
       T.STD_NETWORK_NODE_NO AS NETWORK_NODE_NO,
       T.STD_NETWORK_DESC AS NETWORK_DESC,
       T.MODULE_NETWORK_NO AS SUB_NETWORK_NO,
       T.MODULE_NETWORK_NODE_NO AS SUB_NETWORK_NODE_NO,
       T.MODULE_NETWORK_DESC AS SUB_NETWORK_DESC,
       T.SUPERIOR_NETWORK_ACT  AS NETWORK_ACT_NO,
       T.SUPERIOR_NETWORK_ACT_DESC AS NETWORK_ACT_DESC,
       T.SUB_NETWORK_ACT AS SUB_NETWORK_ACT_NO,
       T.SUB_NETWORK_ACT_DESC,
       T.ENGINE_TYPE,
       T.ENGINE_TYPE_DESC,
       T.MODULE_CAT_CODE,
       T.MODULE_CAT_DESC,
       T.WORK_CENTER,
       T.CONTROL_KEY,
       T.GATE,
       T.DURATION,
       T.DURATION_UNIT,
       T.WORK,
       T.WORK_UNIT,
       T.EWORKSCOPING_FLAG,
       T.LID_NO,
       T.UPDT_USERID,
       T.TIME_STAMP,
       T.ACTION,
       T.OBSOLETE_RECORD_FLAG
FROM PWUST_NETWORK_DEF T;
/
grant select on PWUST_NETWORK_DEF_MAP_V  to pratt_read_only ;
grant select on PWUST_NETWORK_DEF_MAP_V  to sf$connection_pool;
GRANT SELECT, INSERT, UPDATE, DELETE ON PWUST_NETWORK_DEF_MAP_V TO SF$CONNECTION_POOL;
