CREATE OR REPLACE VIEW PWUST_WO_DISPATCH_FIND_V AS
SELECT
       CASE WHEN B.INSP_ORDER_ID IS NOT NULL THEN  'InspectionBlock' ELSE '' END AS IMAGE,
       B.INSP_ORDER_ID AS INSP_ORDER_ID,
        (SELECT A1.PW_ORDER_NO FROM PWUST_SFWID_ORDER_DESC A1 WHERE A1.ORDER_ID = A.ORDER_ID) AS ORDER_NO,
       A.ORDER_TYPE AS ORDER_TYPE,
       A.PART_NO AS PART_NO,
       A.PART_CHG AS PART_CHG,
       A.ITEM_TYPE AS ITEM_TYPE,
       A.ITEM_SUBTYPE AS ITEM_SUBTYPE,
       A.PROGRAM AS PROGRAM,
       A.ORDER_STATUS AS ORDER_STATUS,
       A.ORDER_HOLD_STATUS AS ORDER_HOLD_STATUS,
       A.ORDER_QTY AS ORDER_QTY,
       LOC.WORK_LOC AS ASGND_WORK_LOC,
       A.ORDER_CUST_ID AS ORDER_CUST_ID,
       A.SCHED_PRIORITY AS SCHED_PRIORITY,
       A.ORDER_ID AS ORDER_ID,
       NULL AS OPER_KEY,
       B.ORDER_LOCKED AS ORDER_LOCKED,
       B.SECURITY_GROUP,
       B.UNIT_NO AS END_UNIT_NO,
       B.UNIT_TYPE AS END_UNIT_TYPE
  FROM SFWID_ORDERS A, SFWID_ORDER_DESC B LEFT OUTER JOIN SFFND_WORK_LOC_DEF LOC ON B.ASGND_LOCATION_ID = LOC.LOCATION_ID
  WHERE A.ORDER_ID = B.ORDER_ID;
/

GRANT SELECT ON PWUST_WO_DISPATCH_FIND_V TO pratt_read_only ;
GRANT SELECT ON PWUST_WO_DISPATCH_FIND_V TO sf$connection_pool ;
