CREATE OR REPLACE VIEW PWUST_INT_SAP_SM_ORDER_TOP_V AS
SELECT  DISTINCT
        IDOC_NUMBER,
        UPDT_USERID,
        SAP_UPDT_USERID,
        (SELECT TT.TIME_STAMP FROM PWUST_INT_SAP_SM_ORDER TT WHERE TT.IDOC_NUMBER = T.IDOC_NUMBER AND ROWNUM =1 ) AS TIME_STAMP
FROM PWUST_INT_SAP_SM_ORDER T
ORDER BY TIME_STAMP  DESC;
/
GRANT SELECT ON PWUST_INT_SAP_SM_ORDER_TOP_V TO PRATT_READ_ONLY ;
GRANT SELECT ON PWUST_INT_SAP_SM_ORDER_TOP_V TO SF$CONNECTION_POOL;