CREATE OR REPLACE VIEW PWUST_SFFND_USER_USER_V
(USERID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, FULL_NAME, NAME_SUFFIX, PAYROLL_ID, LOCATION_ID,
DEPARTMENT_ID, CENTER_ID, WORK_LOC, WORK_DEPT, WORK_CENTER, WORK_DEPT_CENTER, SHIFT,
OBSOLETE_RECORD_FLAG, IN_DATABASE_FLAG, EMAIL_ADDRESS, UCF_USER_VCH1, UCF_USER_VCH2, UCF_USER_VCH3,
UCF_USER_VCH4, ACCOUNT_TYPE, ACCOUNT_STATUS, USER_CLASS, UCF_USER_VCH5, UCF_USER_VCH6, UCF_USER_VCH7,
UCF_USER_VCH8, UCF_USER_VCH9, UCF_USER_VCH10, UCF_USER_VCH11, UCF_USER_VCH12, UCF_USER_VCH13,
UCF_USER_VCH14, UCF_USER_VCH15, UCF_USER_NUM1, UCF_USER_NUM2, UCF_USER_NUM3, UCF_USER_NUM4,
UCF_USER_NUM5, UCF_USER_DATE1, UCF_USER_DATE2, UCF_USER_DATE3, UCF_USER_DATE4, UCF_USER_DATE5,
UCF_USER_FLAG1, UCF_USER_FLAG2, UCF_USER_FLAG3, UCF_USER_FLAG4, UCF_USER_FLAG5, USER_TYPE,
INCLUDE_ALL_SUPPLIERS, LAST_EYE_EXAM_DATE, CURRENT_LEVEL, MAX_LEVEL, LEVEL_START_DATE, STATUS,
UNDER_REVIEW_FLAG, PRODUCTION_COUNT, PRODUCTION_RATE, OI_NO_OF_UNITS, OI_NO_OF_DATA_COLLECTIONS,
NO_OF_REJECTS, LAST_ACTIVITY_DATE, LAST_DECERTIFICATION_DATE, NOTES, LEVEL_UPDT_USERID,
LEVEL_TIME_STAMP, OI_START_DATE, OI_STATUS, OI_NOTES, UCF_USER_VCH255_1, UCF_USER_VCH255_2,
UCF_USER_VCH255_3, UCF_USER_VCH4000_1, UCF_USER_VCH4000_2, LABOR_TYPE, USER_DEFINITION,
USER_LOGIN_ATTEMPT, UPDT_USERID, TIME_STAMP, MI_USER_FLAG) AS
SELECT A.USERID, A.LAST_NAME, A.FIRST_NAME, A.MIDDLE_NAME, A.FULL_NAME, A.NAME_SUFFIX,
       A.PAYROLL_ID, A.LOCATION_ID, A.DEPARTMENT_ID, A.CENTER_ID, L.WORK_LOC, D.WORK_DEPT,
       C.WORK_CENTER, L.WORK_LOC || ',' || D.WORK_DEPT || ',' || C.WORK_CENTER, A.SHIFT,
       A.OBSOLETE_RECORD_FLAG, DECODE(B.NAME, NULL, 'N', 'Y'), A.EMAIL_ADDRESS,
       A.UCF_USER_VCH1, A.UCF_USER_VCH2, A.UCF_USER_VCH3, A.UCF_USER_VCH4, AA.ACCOUNT_TYPE,
       AA.ACCOUNT_STATUS, A.USER_CLASS, UCF_USER_VCH5, UCF_USER_VCH6, UCF_USER_VCH7,
       UCF_USER_VCH8, UCF_USER_VCH9, UCF_USER_VCH10, UCF_USER_VCH11, UCF_USER_VCH12,
       UCF_USER_VCH13, UCF_USER_VCH14, UCF_USER_VCH15, UCF_USER_NUM1, UCF_USER_NUM2,
       UCF_USER_NUM3, UCF_USER_NUM4, UCF_USER_NUM5, UCF_USER_DATE1, UCF_USER_DATE2,
       UCF_USER_DATE3, UCF_USER_DATE4, UCF_USER_DATE5, UCF_USER_FLAG1, UCF_USER_FLAG2,
       UCF_USER_FLAG3, UCF_USER_FLAG4, UCF_USER_FLAG5, A.USER_TYPE,
       A.INCLUDE_ALL_SUPPLIERS, A.LAST_EYE_EXAM_DATE, A.CURRENT_LEVEL, A.MAX_LEVEL,
       A.LEVEL_START_DATE, A.STATUS, A.UNDER_REVIEW_FLAG, A.PRODUCTION_COUNT,
       A.PRODUCTION_RATE, A.OI_NO_OF_UNITS, A.OI_NO_OF_DATA_COLLECTIONS, A.NO_OF_REJECTS,
       A.LAST_ACTIVITY_DATE, A.LAST_DECERTIFICATION_DATE, A.NOTES, A.LEVEL_UPDT_USERID,
       A.LEVEL_TIME_STAMP, A.OI_START_DATE, A.OI_STATUS, A.OI_NOTES, A.UCF_USER_VCH255_1,
       A.UCF_USER_VCH255_2, A.UCF_USER_VCH255_3, A.UCF_USER_VCH4000_1,
       A.UCF_USER_VCH4000_2, A.LABOR_TYPE, A.USER_DEFINITION, A.USER_LOGIN_ATTEMPT,
       A.UPDT_USERID, A.TIME_STAMP, A.MI_USER_FLAG
  FROM SFCORE_USER AA, SFFND_USER A
  LEFT OUTER JOIN SFFND_WORK_LOC_DEF L
    ON A.LOCATION_ID = L.LOCATION_ID
  LEFT OUTER JOIN SFFND_WORK_DEPT_DEF D
    ON A.LOCATION_ID = D.LOCATION_ID
   AND A.DEPARTMENT_ID = D.DEPARTMENT_ID
  LEFT OUTER JOIN SFFND_WORK_CENTER_DEF C
    ON A.LOCATION_ID = C.LOCATION_ID
   AND A.DEPARTMENT_ID = C.DEPARTMENT_ID
   AND A.CENTER_ID = C.CENTER_ID
  LEFT OUTER JOIN SYS.USER$ B
    ON A.USERID = B.NAME
 WHERE A.USERID = AA.USERID;
