--VIS_CONV_USERS_AND_ROLES
CREATE OR REPLACE FORCE VIEW "VIS_CONV_USERS_AND_ROLES" ("USERCODE", "BUSINESS_ROLE") AS
SELECT DOMAIN || '\' || USERCODE AS USERCODE, 'user' AS BUSINESS_ROLE
  FROM VIS_CONV_USERS
UNION
SELECT U.DOMAIN || '\' || U.USERCODE AS USERCODE, R.BUSINESS_ROLE
  FROM VIS_CONV_USERS U, VIS_CONV_ROLES R
 WHERE U.USERCODE = R.USERCODE;

--VISV_LONG_STEPS
CREATE OR REPLACE FORCE VIEW "VISV_LONG_STEPS" ("PART_NO", "OPER_NO", "STEP_NO", "STEP_LENGTH", "TEXT") AS 
SELECT P.PART_NO, O.OPER_NO, S.STEP_NO, LENGTH(S.TEXT) AS STEP_LENGTH, S.TEXT
  FROM VIS_STEP S, VIS_OPERATION O, VIS_PLAN P, VIS_CONV_PLAN CP
 WHERE S.OPER_KEY = O.OPER_KEY
   AND O.PLAN_ID = P.PLAN_ID
   AND P.PART_NO = CP.PLAN_NAME
   AND CP.STAGE = 'D'
   AND LENGTH(TEXT) > 4000;

--VISV_ORPHANED_OPERATIONS
CREATE OR REPLACE FORCE VIEW "VISV_ORPHANED_OPERATIONS" ("OPER_KEY") AS 
SELECT O.OPER_KEY
  FROM VIS_OPERATION O
 WHERE NOT EXISTS
 (SELECT O.OPER_KEY FROM VIS_OPERATION_SUBJECT VOS WHERE O.OPER_KEY = VOS.OPER_KEY);

--VISV_ORPHANED_SUBJECTS
CREATE OR REPLACE FORCE VIEW "VISV_ORPHANED_SUBJECTS" ("SUBJECT_ID") AS 
SELECT S.SUBJECT_ID
  FROM VIS_SUBJECT S
 WHERE NOT EXISTS (SELECT SUBJECT_ID
          FROM VIS_SUBJECT_CUSTOMER_INCLUSION SCI
         WHERE S.SUBJECT_ID = SCI.SUBJECT_ID);

--VISV_REMOVABLE_OPERATIONS
CREATE OR REPLACE FORCE VIEW "VISV_REMOVABLE_OPERATIONS" ("OPER_KEY") AS 
SELECT O.OPER_KEY
  FROM VIS_OPERATION O
 WHERE O.PLAN_ID IN (SELECT PLAN_ID FROM VISV_REMOVABLE_PLANS);

--VISV_REMOVABLE_PLANS
CREATE OR REPLACE FORCE VIEW "VISV_REMOVABLE_PLANS" ("PLAN_ID") AS 
SELECT PLAN_ID
  FROM VIS_PLAN P
 WHERE P.PART_NO IN (SELECT PLAN_NAME FROM VIS_CONV_PLAN WHERE STAGE = 'A');

--VISV_REMOVABLE_SUBJECTS
CREATE OR REPLACE FORCE VIEW "VISV_REMOVABLE_SUBJECTS" ("SUBJECT_ID") AS 
SELECT S.SUBJECT_ID
  FROM VIS_SUBJECT S
 WHERE S.PLAN_ID IN (SELECT PLAN_ID FROM VISV_REMOVABLE_PLANS);

--VISV_STAGED_OPERATIONS
CREATE OR REPLACE FORCE VIEW "VISV_STAGED_OPERATIONS" ("OPER_KEY") AS 
SELECT O.OPER_KEY
  FROM VIS_OPERATION O
 WHERE O.PLAN_ID IN (SELECT PLAN_ID FROM VISV_STAGED_PLANS);

--VISV_STAGED_PLANS
CREATE OR REPLACE FORCE VIEW "VISV_STAGED_PLANS" ("PLAN_ID") AS 
SELECT PLAN_ID
  FROM VIS_PLAN P
 WHERE P.PART_NO IN (SELECT PLAN_NAME FROM VIS_CONV_PLAN WHERE STAGE IN ('D'));

--VISV_STAGED_SUBJECTS
CREATE OR REPLACE FORCE VIEW "VISV_STAGED_SUBJECTS" ("SUBJECT_ID") AS 
SELECT S.SUBJECT_ID
  FROM VIS_SUBJECT S
 WHERE S.PLAN_ID IN (SELECT PLAN_ID FROM VISV_STAGED_PLANS);

--VISV_TOO_MANY_NETWORKS
CREATE OR REPLACE FORCE VIEW "VISV_TOO_MANY_NETWORKS" ("PLAN_ID", "PART_NO", "SUBJECT_NO", "SUBJECT_ID", "NUM_SUBS") AS 
(
  SELECT P.PLAN_ID, P.PART_NO, S.SUBJECT_NO, S.SUBJECT_ID, SUBS.NUM_SUBS
    FROM (SELECT PLAN_ID, SUBJECT_ID, COUNT(ACTIVITY_NUMBER) AS NUM_SUBS
            FROM VIS_SUBJECT_SUPERIOR_NETWORK
           GROUP BY (PLAN_ID, SUBJECT_ID)
          HAVING COUNT(ACTIVITY_NUMBER) > 1) SUBS,
         VIS_PLAN P,
         VIS_SUBJECT S
   WHERE SUBS.PLAN_ID = P.PLAN_ID
     AND SUBS.SUBJECT_ID = S.SUBJECT_ID
);

--VISV_TOO_MANY_SUBNETWORKS
CREATE OR REPLACE FORCE VIEW "VISV_TOO_MANY_SUBNETWORKS" ("PLAN_ID", "PART_NO", "SUBJECT_NO", "SUBJECT_ID", "NUM_SUBS") AS 
(
  SELECT P.PLAN_ID, P.PART_NO, S.SUBJECT_NO, S.SUBJECT_ID, SUBS.NUM_SUBS
    FROM (SELECT PLAN_ID, SUBJECT_ID, COUNT(SUB_ACTIVITY_NUMBER) AS NUM_SUBS
            FROM VIS_SUBJECT_SUB_NETWORK
           GROUP BY (PLAN_ID, SUBJECT_ID)
          HAVING COUNT(SUB_ACTIVITY_NUMBER) > 1) SUBS,
         VIS_PLAN P,
         VIS_SUBJECT S
   WHERE SUBS.PLAN_ID = P.PLAN_ID
     AND SUBS.SUBJECT_ID = S.SUBJECT_ID
);
